# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20150309_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetnewsperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='internetnewsperson',
            name='is_photograph',
        ),
        migrations.RemoveField(
            model_name='internetnewsperson',
            name='is_quoted',
        ),
        migrations.RemoveField(
            model_name='internetnewsperson',
            name='occupation_other',
        ),
        migrations.RemoveField(
            model_name='internetnewsperson',
            name='survivor_comments',
        ),
        migrations.RemoveField(
            model_name='internetnewsperson',
            name='victim_comments',
        ),
        migrations.RemoveField(
            model_name='newspaperperson',
            name='occupation_other',
        ),
        migrations.RemoveField(
            model_name='newspaperperson',
            name='survivor_comments',
        ),
        migrations.RemoveField(
            model_name='newspaperperson',
            name='victim_comments',
        ),
        migrations.RemoveField(
            model_name='radioperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='radioperson',
            name='is_photograph',
        ),
        migrations.RemoveField(
            model_name='radioperson',
            name='is_quoted',
        ),
        migrations.RemoveField(
            model_name='radioperson',
            name='occupation_other',
        ),
        migrations.RemoveField(
            model_name='radioperson',
            name='survivor_comments',
        ),
        migrations.RemoveField(
            model_name='radioperson',
            name='victim_comments',
        ),
        migrations.RemoveField(
            model_name='televisionperson',
            name='is_photograph',
        ),
        migrations.RemoveField(
            model_name='televisionperson',
            name='is_quoted',
        ),
        migrations.RemoveField(
            model_name='televisionperson',
            name='occupation_other',
        ),
        migrations.RemoveField(
            model_name='televisionperson',
            name='survivor_comments',
        ),
        migrations.RemoveField(
            model_name='televisionperson',
            name='victim_comments',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='family_role',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='function',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='is_quoted',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='occupation_other',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='survivor_comments',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='survivor_of',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='victim_comments',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='victim_of',
        ),
        migrations.RemoveField(
            model_name='twitterperson',
            name='victim_or_survivor',
        ),
    ]
