# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20150324_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewsjournalist',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsjournalist',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='Journalists Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='age',
            field=models.PositiveIntegerField(verbose_name='(11) Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='family_role',
            field=models.CharField(help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(14) Family Role Given?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='function',
            field=models.PositiveIntegerField(verbose_name='(13) Function in the news story', choices=[(0, '(0) Do not know'), (1, '(1) Subject'), (2, '(2) Spokesperson'), (3, '(3) Expert or commentator'), (4, '(4) Personal Experience'), (5, '(5) Eye Witness'), (6, '(6) Popular Opinion'), (7, '(7) Other')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='is_photograph',
            field=models.PositiveIntegerField(verbose_name='(19) Is there a photograph of the person in the story?', choices=[(1, '(0) Yes'), (2, '(1) No'), (3, '(2) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='is_quoted',
            field=models.CharField(help_text='<p>A person is <strong>directly quoted</strong> if their own words are printed, e.g. "The war against terror is our first priority" said President Bush.</p><p>If the story paraphrases what the person said, that is not a direct quote, e.g. President Bush said that top priority would be given to fighting the war against terror.</p>', max_length=1, verbose_name='(18) Is the person directly quoted', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='occupation',
            field=models.PositiveIntegerField(verbose_name='(12) Occupation or Position', choices=[(0, '(0) Not stated'), (1, '(1) Royalty, monarch, deposed monarch, etc.'), (2, '(2) Government, politician, minister, spokesperson...'), (3, '(3) Government employee, public servant, etc.'), (4, '(4) Police, military, para-military, militia, fire officer'), (5, '(5) Academic expert, lecturer, teacher'), (6, '(6) Doctor, dentist, health specialist'), (7, '(7) Health worker, social worker, childcare worker'), (8, '(8) Science/ technology professional, engineer, etc.'), (9, '(9) Media professional, journalist, film-maker, etc.'), (10, '(10) Lawyer, judge, magistrate, legal advocate, etc.'), (11, '(11) Business person, exec, manager, stock broker...'), (12, '(12) Office or service worker, non-management worker'), (13, '(13) Tradesperson, artisan, labourer, truck driver, etc.'), (14, '(14) Agriculture, mining, fishing, forestry'), (15, '(15) Religious figure, priest, monk, rabbi, mullah, nun'), (16, '(16) Activist or worker in civil society org., NGO, trade union'), (17, '(17) Sex worker'), (18, '(18) Celebrity, artist, actor, writer, singer, TV personality'), (19, '(19) Sportsperson, athlete, player, coach, referee'), (20, '(20) Student, pupil, schoolchild'), (21, '(21) Homemaker, parent (male or female)) only if no other occupation is given e.g. doctor/mother=code 6'), (22, '(22) Child, young person no other occupation given'), (23, '(23) Villager or resident no other occupation given'), (24, '(24) Retired person, pensioner no other occupation given'), (25, '(25) Criminal, suspect no other occupation given'), (26, '(26) Unemployed no other occupation given'), (27, '(27) Other only as last resort & explain')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='(10) Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='survivor_of',
            field=models.PositiveIntegerField(verbose_name='(17) The story identifies the person as a survivor of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a victim)'), (1, '(1) Survivor of an accident, natural disaster, poverty'), (2, '(2) Survivor of domestic violence, rape, murder, etc.'), (3, '(3) Survivor of non-domestic sexual violence, rape, assault, etc. (sexual violence only)'), (4, '(4) Survivor of other non-domestic crime, robbery, etc.'), (5, '(5) Survivor of violation based on religion, tradition...'), (6, '(6) Survivor of war, terrorism, vigilantism, state violence...'), (7, '(7) Survivor of discrimination based on gender, race, ethnicity, age, religion, ability, etc.'), (8, '(8) Other survivor (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='victim_of',
            field=models.PositiveIntegerField(verbose_name='(16) The story identifies the person as a victim of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a survivor)'), (1, '(1) Victim of an accident, natural disaster, poverty'), (2, '(2) Victim of domestic violence, rape, murder, etc.'), (3, '(3) Victim of non-domestic sexual violence, rape, assault, etc (sexual violence only)'), (4, '(4) Victim of other non-domestic crime, robbery, etc.'), (5, '(5) Victim of violation based on religion, tradition...'), (6, '(6) Victim of war, terrorism, vigilantism, state violence...'), (7, '(7) Victim of discrimination based on gender, race, ethnicity, age, religion, ability, etc'), (8, '(8) Other victim (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='victim_or_survivor',
            field=models.CharField(help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(15) Does the story identify the person as either a victim or survivor?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='about_women',
            field=models.CharField(max_length=1, verbose_name='(21) Is the story about a particular woman or group of women?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='equality_rights',
            field=models.CharField(help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(6) Reference to gender equality / human rights legislation/ policy', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='further_analysis',
            field=models.CharField(help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(24) Does this story warrant further analysis?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='inequality_women',
            field=models.PositiveIntegerField(verbose_name='(22) This story clearly highlights issues of inequality between women and men', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='offline_presence',
            field=models.CharField(max_length=1, verbose_name='Offline presence?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='person_secondary',
            field=models.PositiveIntegerField(help_text="<br><br>\n    Select ''Secondary Source'' only if the story is based solely on information from a report, article, or other piece of written information.<br><br>\n<strong>Code information for:</strong><br>\n  - Any person whom the story is about even if they are not interviewed or quoted<br>\n  - Each person who is interviewed<br>\n  - Each person in the story who is quoted, either directly or indirectly. Code only individual people.<br>\n<br>\n<strong>Do not code:</strong>\n  - Groups (e.g. a group of nurses, a group of soldiers);</br>\n  - Organisations, companies, collectivities (e.g. political parties);</br>\n  - Characters in novels or movies (unless the story is about them);</br>\n  - Deceased historical figures (unless the story is about them);</br>\n  - Interpreters (Code the person being interviewed as if they spoke without an interpreter).</br>\n", verbose_name='(9) Source', choices=[(0, '(0) Do not know'), (1, '(1) Person'), (2, '(2) Secondary Source')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='scope',
            field=models.PositiveIntegerField(help_text='Code the widest geographical scope that applies: if the event has both local and national importance, code national.', verbose_name='(3) Scope', choices=[(1, '(1) Local'), (2, '(2) National'), (3, '(3) Sub-Regional'), (4, '(4) Foreign/International')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='shared_on_facebook',
            field=models.CharField(help_text='Has this story been shared by the media house on its Facebook Page?', max_length=1, verbose_name='(5) Shared on Facebook', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='shared_via_twitter',
            field=models.CharField(help_text='Has this story been shared by the media house via Twitter?\n\n<br>Enter the exact URL of the story into <a href="http://topsy.com/" target="_blank">http://topsy.com</a> - answer yes if the media house\'s name appears in the search results.', max_length=1, verbose_name='(4) Shared via twitter?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='stereotypes',
            field=models.PositiveIntegerField(help_text='This story clearly challenges gender stereotypes', verbose_name='(23) Stereotypes', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='topic',
            field=models.PositiveIntegerField(help_text="Choose one topic that best describes how the story is reported. Remember that a single event can be reported in different ways. Within each broad category, we include a code for 'other stories'. Please use these codes only as a <strong>last resort</strong>.", verbose_name='(2) Topic', choices=[(1, '(1) Women politicians, women electoral candidates...'), (2, '(2) Peace, negotiations, treaties'), (3, '(3) Other domestic politics, government, etc.'), (4, '(4) Global partnerships'), (5, '(5) Foreign/international politics, UN, peacekeeping'), (6, '(6) National defence, military spending, internal security, etc.'), (7, '(7) Other stories on politics (specify in comments)'), (8, '(8) Economic policies, strategies, modules, indicators, stock markets, etc'), (9, '(9) Economic crisis, state bailouts of companies, company takeovers and mergers, etc.'), (10, '(10) Poverty, housing, social welfare, aid, etc.'), (11, '(11) Womens participation in economic processes'), (12, '(12) Employment'), (13, '(13) Informal work, street vending, etc.'), (14, '(14) Other labour issues (strikes, trade unions, etc.)'), (15, '(15) Rural economy, agriculture, farming, land rights'), (16, '(16) Consumer issues, consumer protection, fraud...'), (17, '(17) Transport, traffic, roads...'), (18, '(18) Other stories on economy (specify in comments)'), (19, '(19) Science, technology, research, discoveries...'), (20, '(20) Medicine, health, hygiene, safety, (not EBOLA or HIV/AIDS)'), (21, '(21) EBOLA, treatment, response...'), (22, '(22) HIV and AIDS, policy, treatment, etc'), (23, '(23) Other epidemics, viruses, contagions, Influenza, BSE, SARS'), (24, '(24) Birth control, fertility, sterilization, termination...'), (25, '(25) Climate change, global warming'), (26, '(26) Environment, pollution, tourism'), (27, '(27) Other stories on science (specify in comments)'), (28, '(28) Millennium Development Goals (MDGs), Post 2015 agenda, Sustainable Development Goals'), (29, '(29) Family relations, inter-generational conflict, parents'), (30, '(30) Human rights, womens rights, rights of sexual minorities, rights of religious minorities, etc.'), (31, '(31) Religion, culture, tradition, controversies...'), (32, '(32) Migration, refugees, xenophobia, ethnic conflict...'), (33, '(33) Other development issues, sustainability, etc.'), (34, '(34) Education, childcare, nursery, university, literacy'), (35, '(35) Womens movement, activism, demonstrations, etc'), (36, '(36) Changing gender relations (outside the home)'), (37, '(37) Family law, family codes, property law, inheritance...'), (38, '(38) Legal system, judiciary, legislation apart from family'), (39, '(39) Disaster, accident, famine, flood, plane crash, etc.'), (40, '(40) Riots, demonstrations, public disorder, etc.'), (41, '(41) Other stories on social/legal (specify in comments)'), (42, '(42) Non-violent crime, bribery, theft, drugs, corruption'), (43, '(43) Violent crime, murder, abduction, assault, etc.'), (44, '(44) Gender violence based on culture, family, inter-personal relations, feminicide, harassment, rape, sexual assault, trafficking, FGM...'), (45, '(45) Gender violence perpetuated by the State'), (46, '(46) Child abuse, sexual violence against children, neglect'), (47, '(47) War, civil war, terrorism, other state-based violence'), (48, '(48) Other crime/violence (specify in comments)'), (49, '(49) Celebrity news, births, marriages, royalty, etc.'), (50, '(50) Arts, entertainment, leisure, cinema, books, dance'), (51, '(51) Media, (including internet), portrayal of women/men'), (52, '(52) Beauty contests, models, fashion, cosmetic surgery'), (53, '(53) Sports, events, players, facilities, training, funding'), (54, '(54) Other celebrity/arts/media news (specify in comments)'), (55, '(55) Other (only use as a last resort & explain)')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='topic_comments',
            field=models.TextField(help_text='Complete if no topic above is applicable', verbose_name='(2a) Topic Comments', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='url_and_multimedia',
            field=models.TextField(verbose_name='(20) Copy and paste the URL of the story. Describe any photographs, images, other multimedia features included in the story. Note down the conclusions you draw from the images, audio and video.', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='webpage_layer_no',
            field=models.PositiveIntegerField(help_text='Webpage Layer Number. Homepage=1, One click away=2, Five clicks away= 5, etc. Note that if a story appears on the front page, code with 1', verbose_name='(1) Webpage Layer Number', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperjournalist',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperjournalist',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='Journalists Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='age',
            field=models.PositiveIntegerField(verbose_name='(9) Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='family_role',
            field=models.CharField(help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(12) Family Role Given?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='function',
            field=models.PositiveIntegerField(verbose_name='(11) Function in the news story', choices=[(0, '(0) Do not know'), (1, '(1) Subject'), (2, '(2) Spokesperson'), (3, '(3) Expert or commentator'), (4, '(4) Personal Experience'), (5, '(5) Eye Witness'), (6, '(6) Popular Opinion'), (7, '(7) Other')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='is_photograph',
            field=models.PositiveIntegerField(verbose_name='(17) Is there a photograph of the person in the story?', choices=[(1, '(0) Yes'), (2, '(1) No'), (3, '(2) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='is_quoted',
            field=models.CharField(help_text='<p>A person is <strong>directly quoted</strong> if their own words are printed, e.g. "The war against terror is our first priority" said President Bush.</p><p>If the story paraphrases what the person said, that is not a direct quote, e.g. President Bush said that top priority would be given to fighting the war against terror.</p>', max_length=1, verbose_name='(16) Is the person directly quoted', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='occupation',
            field=models.PositiveIntegerField(verbose_name='(10) Occupation or Position', choices=[(0, '(0) Not stated'), (1, '(1) Royalty, monarch, deposed monarch, etc.'), (2, '(2) Government, politician, minister, spokesperson...'), (3, '(3) Government employee, public servant, etc.'), (4, '(4) Police, military, para-military, militia, fire officer'), (5, '(5) Academic expert, lecturer, teacher'), (6, '(6) Doctor, dentist, health specialist'), (7, '(7) Health worker, social worker, childcare worker'), (8, '(8) Science/ technology professional, engineer, etc.'), (9, '(9) Media professional, journalist, film-maker, etc.'), (10, '(10) Lawyer, judge, magistrate, legal advocate, etc.'), (11, '(11) Business person, exec, manager, stock broker...'), (12, '(12) Office or service worker, non-management worker'), (13, '(13) Tradesperson, artisan, labourer, truck driver, etc.'), (14, '(14) Agriculture, mining, fishing, forestry'), (15, '(15) Religious figure, priest, monk, rabbi, mullah, nun'), (16, '(16) Activist or worker in civil society org., NGO, trade union'), (17, '(17) Sex worker'), (18, '(18) Celebrity, artist, actor, writer, singer, TV personality'), (19, '(19) Sportsperson, athlete, player, coach, referee'), (20, '(20) Student, pupil, schoolchild'), (21, '(21) Homemaker, parent (male or female)) only if no other occupation is given e.g. doctor/mother=code 6'), (22, '(22) Child, young person no other occupation given'), (23, '(23) Villager or resident no other occupation given'), (24, '(24) Retired person, pensioner no other occupation given'), (25, '(25) Criminal, suspect no other occupation given'), (26, '(26) Unemployed no other occupation given'), (27, '(27) Other only as last resort & explain')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='(8) Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='survivor_of',
            field=models.PositiveIntegerField(verbose_name='(15) The story identifies the person as a survivor of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a victim)'), (1, '(1) Survivor of an accident, natural disaster, poverty'), (2, '(2) Survivor of domestic violence, rape, murder, etc.'), (3, '(3) Survivor of non-domestic sexual violence, rape, assault, etc. (sexual violence only)'), (4, '(4) Survivor of other non-domestic crime, robbery, etc.'), (5, '(5) Survivor of violation based on religion, tradition...'), (6, '(6) Survivor of war, terrorism, vigilantism, state violence...'), (7, '(7) Survivor of discrimination based on gender, race, ethnicity, age, religion, ability, etc.'), (8, '(8) Other survivor (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='victim_of',
            field=models.PositiveIntegerField(verbose_name='(14) The story identifies the person as a victim of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a survivor)'), (1, '(1) Victim of an accident, natural disaster, poverty'), (2, '(2) Victim of domestic violence, rape, murder, etc.'), (3, '(3) Victim of non-domestic sexual violence, rape, assault, etc (sexual violence only)'), (4, '(4) Victim of other non-domestic crime, robbery, etc.'), (5, '(5) Victim of violation based on religion, tradition...'), (6, '(6) Victim of war, terrorism, vigilantism, state violence...'), (7, '(7) Victim of discrimination based on gender, race, ethnicity, age, religion, ability, etc'), (8, '(8) Other victim (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='victim_or_survivor',
            field=models.CharField(help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(13) Does the story identify the person as either a victim or survivor?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='about_women',
            field=models.CharField(max_length=1, verbose_name='(19) Is the story about a particular woman or group of women?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='comments',
            field=models.TextField(verbose_name='(18) Describe any photographs included in the story and the conclusions you draw from them.', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='equality_rights',
            field=models.CharField(help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(5) Reference to gender equality / human rights legislation/ policy', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='further_analysis',
            field=models.CharField(help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(22) Does this story warrant further analysis?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='inequality_women',
            field=models.PositiveIntegerField(verbose_name='(20) This story clearly highlights issues of inequality between women and men', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='page_number',
            field=models.PositiveIntegerField(help_text='Write in the number of the page on which the story begins. Story appears on first page = 1, Seventh page = 7, etc.', verbose_name='(1) Page Number', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='person_secondary',
            field=models.PositiveIntegerField(help_text="<br><br>\n    Select ''Secondary Source'' only if the story is based solely on information from a report, article, or other piece of written information.<br><br>\n<strong>Code information for:</strong><br>\n  - Any person whom the story is about even if they are not interviewed or quoted<br>\n  - Each person who is interviewed<br>\n  - Each person in the story who is quoted, either directly or indirectly. Code only individual people.<br>\n<br>\n<strong>Do not code:</strong>\n  - Groups (e.g. a group of nurses, a group of soldiers);</br>\n  - Organisations, companies, collectivities (e.g. political parties);</br>\n  - Characters in novels or movies (unless the story is about them);</br>\n  - Deceased historical figures (unless the story is about them);</br>\n  - Interpreters (Code the person being interviewed as if they spoke without an interpreter).</br>\n", verbose_name='(7) Source', choices=[(0, '(0) Do not know'), (1, '(1) Person'), (2, '(2) Secondary Source')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='scope',
            field=models.PositiveIntegerField(help_text='Code the widest geographical scope that applies: if the event has both local and national importance, code national.', verbose_name='(3) Scope', choices=[(1, '(1) Local'), (2, '(2) National'), (3, '(3) Sub-Regional'), (4, '(4) Foreign/International')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='space',
            field=models.PositiveIntegerField(verbose_name='(4) Space', choices=[(1, '(0) Full page'), (2, '(1) Half page'), (3, '(2) One third page'), (4, '(3) Quarter page'), (5, '(4) Less than quarter page')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='stereotypes',
            field=models.PositiveIntegerField(help_text='This story clearly challenges gender stereotypes', verbose_name='(21) Stereotypes', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='topic',
            field=models.PositiveIntegerField(help_text="Choose one topic that best describes how the story is reported. Remember that a single event can be reported in different ways. Within each broad category, we include a code for 'other stories'. Please use these codes only as a <strong>last resort</strong>.", verbose_name='(2) Topic', choices=[(1, '(1) Women politicians, women electoral candidates...'), (2, '(2) Peace, negotiations, treaties'), (3, '(3) Other domestic politics, government, etc.'), (4, '(4) Global partnerships'), (5, '(5) Foreign/international politics, UN, peacekeeping'), (6, '(6) National defence, military spending, internal security, etc.'), (7, '(7) Other stories on politics (specify in comments)'), (8, '(8) Economic policies, strategies, modules, indicators, stock markets, etc'), (9, '(9) Economic crisis, state bailouts of companies, company takeovers and mergers, etc.'), (10, '(10) Poverty, housing, social welfare, aid, etc.'), (11, '(11) Womens participation in economic processes'), (12, '(12) Employment'), (13, '(13) Informal work, street vending, etc.'), (14, '(14) Other labour issues (strikes, trade unions, etc.)'), (15, '(15) Rural economy, agriculture, farming, land rights'), (16, '(16) Consumer issues, consumer protection, fraud...'), (17, '(17) Transport, traffic, roads...'), (18, '(18) Other stories on economy (specify in comments)'), (19, '(19) Science, technology, research, discoveries...'), (20, '(20) Medicine, health, hygiene, safety, (not EBOLA or HIV/AIDS)'), (21, '(21) EBOLA, treatment, response...'), (22, '(22) HIV and AIDS, policy, treatment, etc'), (23, '(23) Other epidemics, viruses, contagions, Influenza, BSE, SARS'), (24, '(24) Birth control, fertility, sterilization, termination...'), (25, '(25) Climate change, global warming'), (26, '(26) Environment, pollution, tourism'), (27, '(27) Other stories on science (specify in comments)'), (28, '(28) Millennium Development Goals (MDGs), Post 2015 agenda, Sustainable Development Goals'), (29, '(29) Family relations, inter-generational conflict, parents'), (30, '(30) Human rights, womens rights, rights of sexual minorities, rights of religious minorities, etc.'), (31, '(31) Religion, culture, tradition, controversies...'), (32, '(32) Migration, refugees, xenophobia, ethnic conflict...'), (33, '(33) Other development issues, sustainability, etc.'), (34, '(34) Education, childcare, nursery, university, literacy'), (35, '(35) Womens movement, activism, demonstrations, etc'), (36, '(36) Changing gender relations (outside the home)'), (37, '(37) Family law, family codes, property law, inheritance...'), (38, '(38) Legal system, judiciary, legislation apart from family'), (39, '(39) Disaster, accident, famine, flood, plane crash, etc.'), (40, '(40) Riots, demonstrations, public disorder, etc.'), (41, '(41) Other stories on social/legal (specify in comments)'), (42, '(42) Non-violent crime, bribery, theft, drugs, corruption'), (43, '(43) Violent crime, murder, abduction, assault, etc.'), (44, '(44) Gender violence based on culture, family, inter-personal relations, feminicide, harassment, rape, sexual assault, trafficking, FGM...'), (45, '(45) Gender violence perpetuated by the State'), (46, '(46) Child abuse, sexual violence against children, neglect'), (47, '(47) War, civil war, terrorism, other state-based violence'), (48, '(48) Other crime/violence (specify in comments)'), (49, '(49) Celebrity news, births, marriages, royalty, etc.'), (50, '(50) Arts, entertainment, leisure, cinema, books, dance'), (51, '(51) Media, (including internet), portrayal of women/men'), (52, '(52) Beauty contests, models, fashion, cosmetic surgery'), (53, '(53) Sports, events, players, facilities, training, funding'), (54, '(54) Other celebrity/arts/media news (specify in comments)'), (55, '(55) Other (only use as a last resort & explain)')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiojournalist',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiojournalist',
            name='role',
            field=models.PositiveIntegerField(verbose_name='Role', choices=[(1, '(0) Anchor, announcer or presenter: Usually in the television studio'), (2, '(1) Reporter: Usually outside the studio. Include reporters who do not appear on screen, but whose voice is heard (e.g. as voice-over).'), (3, '(2) Other journalist: Sportscaster, weather forecaster, commentator/analyst etc.')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiojournalist',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='Journalists Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='family_role',
            field=models.CharField(help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(10) Family Role Given?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='function',
            field=models.PositiveIntegerField(verbose_name='(9) Function in the news story', choices=[(0, '(0) Do not know'), (1, '(1) Subject'), (2, '(2) Spokesperson'), (3, '(3) Expert or commentator'), (4, '(4) Personal Experience'), (5, '(5) Eye Witness'), (6, '(6) Popular Opinion'), (7, '(7) Other')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='occupation',
            field=models.PositiveIntegerField(verbose_name='(8) Occupation or Position', choices=[(0, '(0) Not stated'), (1, '(1) Royalty, monarch, deposed monarch, etc.'), (2, '(2) Government, politician, minister, spokesperson...'), (3, '(3) Government employee, public servant, etc.'), (4, '(4) Police, military, para-military, militia, fire officer'), (5, '(5) Academic expert, lecturer, teacher'), (6, '(6) Doctor, dentist, health specialist'), (7, '(7) Health worker, social worker, childcare worker'), (8, '(8) Science/ technology professional, engineer, etc.'), (9, '(9) Media professional, journalist, film-maker, etc.'), (10, '(10) Lawyer, judge, magistrate, legal advocate, etc.'), (11, '(11) Business person, exec, manager, stock broker...'), (12, '(12) Office or service worker, non-management worker'), (13, '(13) Tradesperson, artisan, labourer, truck driver, etc.'), (14, '(14) Agriculture, mining, fishing, forestry'), (15, '(15) Religious figure, priest, monk, rabbi, mullah, nun'), (16, '(16) Activist or worker in civil society org., NGO, trade union'), (17, '(17) Sex worker'), (18, '(18) Celebrity, artist, actor, writer, singer, TV personality'), (19, '(19) Sportsperson, athlete, player, coach, referee'), (20, '(20) Student, pupil, schoolchild'), (21, '(21) Homemaker, parent (male or female)) only if no other occupation is given e.g. doctor/mother=code 6'), (22, '(22) Child, young person no other occupation given'), (23, '(23) Villager or resident no other occupation given'), (24, '(24) Retired person, pensioner no other occupation given'), (25, '(25) Criminal, suspect no other occupation given'), (26, '(26) Unemployed no other occupation given'), (27, '(27) Other only as last resort & explain')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='(7) Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='survivor_of',
            field=models.PositiveIntegerField(verbose_name='(13) The story identifies the person as a survivor of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a victim)'), (1, '(1) Survivor of an accident, natural disaster, poverty'), (2, '(2) Survivor of domestic violence, rape, murder, etc.'), (3, '(3) Survivor of non-domestic sexual violence, rape, assault, etc. (sexual violence only)'), (4, '(4) Survivor of other non-domestic crime, robbery, etc.'), (5, '(5) Survivor of violation based on religion, tradition...'), (6, '(6) Survivor of war, terrorism, vigilantism, state violence...'), (7, '(7) Survivor of discrimination based on gender, race, ethnicity, age, religion, ability, etc.'), (8, '(8) Other survivor (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='victim_of',
            field=models.PositiveIntegerField(verbose_name='(12) The story identifies the person as a victim of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a survivor)'), (1, '(1) Victim of an accident, natural disaster, poverty'), (2, '(2) Victim of domestic violence, rape, murder, etc.'), (3, '(3) Victim of non-domestic sexual violence, rape, assault, etc (sexual violence only)'), (4, '(4) Victim of other non-domestic crime, robbery, etc.'), (5, '(5) Victim of violation based on religion, tradition...'), (6, '(6) Victim of war, terrorism, vigilantism, state violence...'), (7, '(7) Victim of discrimination based on gender, race, ethnicity, age, religion, ability, etc'), (8, '(8) Other victim (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='victim_or_survivor',
            field=models.CharField(help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(11) Does the story identify the person as either a victim or survivor?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='about_women',
            field=models.CharField(max_length=1, verbose_name='(14) Is the story about a particular woman or group of women?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='comments',
            field=models.TextField(verbose_name='(N/A) Describe any photographs included in the story and the conclusions you draw from them.', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='equality_rights',
            field=models.CharField(help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(4) Reference to gender equality / human rights legislation/ policy', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='further_analysis',
            field=models.CharField(help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(17) Does this story warrant further analysis?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='inequality_women',
            field=models.PositiveIntegerField(verbose_name='(15) This story clearly highlights issues of inequality between women and men', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='item_number',
            field=models.PositiveIntegerField(help_text='Write in the number that describes the position of the story within the newscast. E.g. the first story in the newscast is item 1; the seventh story is item 7.', verbose_name='(1) Item Number', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='scope',
            field=models.PositiveIntegerField(help_text='Code the widest geographical scope that applies: if the event has both local and national importance, code national.', verbose_name='(3) Scope', choices=[(1, '(1) Local'), (2, '(2) National'), (3, '(3) Sub-Regional'), (4, '(4) Foreign/International')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='stereotypes',
            field=models.PositiveIntegerField(help_text='This story clearly challenges gender stereotypes', verbose_name='(16) Stereotypes', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='topic',
            field=models.PositiveIntegerField(help_text="Choose one topic that best describes how the story is reported. Remember that a single event can be reported in different ways. Within each broad category, we include a code for 'other stories'. Please use these codes only as a <strong>last resort</strong>.", verbose_name='(2) Topic', choices=[(1, '(1) Women politicians, women electoral candidates...'), (2, '(2) Peace, negotiations, treaties'), (3, '(3) Other domestic politics, government, etc.'), (4, '(4) Global partnerships'), (5, '(5) Foreign/international politics, UN, peacekeeping'), (6, '(6) National defence, military spending, internal security, etc.'), (7, '(7) Other stories on politics (specify in comments)'), (8, '(8) Economic policies, strategies, modules, indicators, stock markets, etc'), (9, '(9) Economic crisis, state bailouts of companies, company takeovers and mergers, etc.'), (10, '(10) Poverty, housing, social welfare, aid, etc.'), (11, '(11) Womens participation in economic processes'), (12, '(12) Employment'), (13, '(13) Informal work, street vending, etc.'), (14, '(14) Other labour issues (strikes, trade unions, etc.)'), (15, '(15) Rural economy, agriculture, farming, land rights'), (16, '(16) Consumer issues, consumer protection, fraud...'), (17, '(17) Transport, traffic, roads...'), (18, '(18) Other stories on economy (specify in comments)'), (19, '(19) Science, technology, research, discoveries...'), (20, '(20) Medicine, health, hygiene, safety, (not EBOLA or HIV/AIDS)'), (21, '(21) EBOLA, treatment, response...'), (22, '(22) HIV and AIDS, policy, treatment, etc'), (23, '(23) Other epidemics, viruses, contagions, Influenza, BSE, SARS'), (24, '(24) Birth control, fertility, sterilization, termination...'), (25, '(25) Climate change, global warming'), (26, '(26) Environment, pollution, tourism'), (27, '(27) Other stories on science (specify in comments)'), (28, '(28) Millennium Development Goals (MDGs), Post 2015 agenda, Sustainable Development Goals'), (29, '(29) Family relations, inter-generational conflict, parents'), (30, '(30) Human rights, womens rights, rights of sexual minorities, rights of religious minorities, etc.'), (31, '(31) Religion, culture, tradition, controversies...'), (32, '(32) Migration, refugees, xenophobia, ethnic conflict...'), (33, '(33) Other development issues, sustainability, etc.'), (34, '(34) Education, childcare, nursery, university, literacy'), (35, '(35) Womens movement, activism, demonstrations, etc'), (36, '(36) Changing gender relations (outside the home)'), (37, '(37) Family law, family codes, property law, inheritance...'), (38, '(38) Legal system, judiciary, legislation apart from family'), (39, '(39) Disaster, accident, famine, flood, plane crash, etc.'), (40, '(40) Riots, demonstrations, public disorder, etc.'), (41, '(41) Other stories on social/legal (specify in comments)'), (42, '(42) Non-violent crime, bribery, theft, drugs, corruption'), (43, '(43) Violent crime, murder, abduction, assault, etc.'), (44, '(44) Gender violence based on culture, family, inter-personal relations, feminicide, harassment, rape, sexual assault, trafficking, FGM...'), (45, '(45) Gender violence perpetuated by the State'), (46, '(46) Child abuse, sexual violence against children, neglect'), (47, '(47) War, civil war, terrorism, other state-based violence'), (48, '(48) Other crime/violence (specify in comments)'), (49, '(49) Celebrity news, births, marriages, royalty, etc.'), (50, '(50) Arts, entertainment, leisure, cinema, books, dance'), (51, '(51) Media, (including internet), portrayal of women/men'), (52, '(52) Beauty contests, models, fashion, cosmetic surgery'), (53, '(53) Sports, events, players, facilities, training, funding'), (54, '(54) Other celebrity/arts/media news (specify in comments)'), (55, '(55) Other (only use as a last resort & explain)')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionjournalist',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionjournalist',
            name='role',
            field=models.PositiveIntegerField(verbose_name='Role', choices=[(1, '(0) Anchor, announcer or presenter: Usually in the television studio'), (2, '(1) Reporter: Usually outside the studio. Include reporters who do not appear on screen, but whose voice is heard (e.g. as voice-over).'), (3, '(2) Other journalist: Sportscaster, weather forecaster, commentator/analyst etc.')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionjournalist',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='Journalists Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='age',
            field=models.PositiveIntegerField(verbose_name='(9) Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='family_role',
            field=models.CharField(help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(12) Family Role Given?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='function',
            field=models.PositiveIntegerField(verbose_name='(11) Function in the news story', choices=[(0, '(0) Do not know'), (1, '(1) Subject'), (2, '(2) Spokesperson'), (3, '(3) Expert or commentator'), (4, '(4) Personal Experience'), (5, '(5) Eye Witness'), (6, '(6) Popular Opinion'), (7, '(7) Other')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='occupation',
            field=models.PositiveIntegerField(verbose_name='(10) Occupation or Position', choices=[(0, '(0) Not stated'), (1, '(1) Royalty, monarch, deposed monarch, etc.'), (2, '(2) Government, politician, minister, spokesperson...'), (3, '(3) Government employee, public servant, etc.'), (4, '(4) Police, military, para-military, militia, fire officer'), (5, '(5) Academic expert, lecturer, teacher'), (6, '(6) Doctor, dentist, health specialist'), (7, '(7) Health worker, social worker, childcare worker'), (8, '(8) Science/ technology professional, engineer, etc.'), (9, '(9) Media professional, journalist, film-maker, etc.'), (10, '(10) Lawyer, judge, magistrate, legal advocate, etc.'), (11, '(11) Business person, exec, manager, stock broker...'), (12, '(12) Office or service worker, non-management worker'), (13, '(13) Tradesperson, artisan, labourer, truck driver, etc.'), (14, '(14) Agriculture, mining, fishing, forestry'), (15, '(15) Religious figure, priest, monk, rabbi, mullah, nun'), (16, '(16) Activist or worker in civil society org., NGO, trade union'), (17, '(17) Sex worker'), (18, '(18) Celebrity, artist, actor, writer, singer, TV personality'), (19, '(19) Sportsperson, athlete, player, coach, referee'), (20, '(20) Student, pupil, schoolchild'), (21, '(21) Homemaker, parent (male or female)) only if no other occupation is given e.g. doctor/mother=code 6'), (22, '(22) Child, young person no other occupation given'), (23, '(23) Villager or resident no other occupation given'), (24, '(24) Retired person, pensioner no other occupation given'), (25, '(25) Criminal, suspect no other occupation given'), (26, '(26) Unemployed no other occupation given'), (27, '(27) Other only as last resort & explain')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='(8) Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='survivor_of',
            field=models.PositiveIntegerField(verbose_name='(15) The story identifies the person as a survivor of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a victim)'), (1, '(1) Survivor of an accident, natural disaster, poverty'), (2, '(2) Survivor of domestic violence, rape, murder, etc.'), (3, '(3) Survivor of non-domestic sexual violence, rape, assault, etc. (sexual violence only)'), (4, '(4) Survivor of other non-domestic crime, robbery, etc.'), (5, '(5) Survivor of violation based on religion, tradition...'), (6, '(6) Survivor of war, terrorism, vigilantism, state violence...'), (7, '(7) Survivor of discrimination based on gender, race, ethnicity, age, religion, ability, etc.'), (8, '(8) Other survivor (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='victim_of',
            field=models.PositiveIntegerField(verbose_name='(14) The story identifies the person as a victim of:', choices=[(0, '(0) Not applicable (the story identifies the person only as a survivor)'), (1, '(1) Victim of an accident, natural disaster, poverty'), (2, '(2) Victim of domestic violence, rape, murder, etc.'), (3, '(3) Victim of non-domestic sexual violence, rape, assault, etc (sexual violence only)'), (4, '(4) Victim of other non-domestic crime, robbery, etc.'), (5, '(5) Victim of violation based on religion, tradition...'), (6, '(6) Victim of war, terrorism, vigilantism, state violence...'), (7, '(7) Victim of discrimination based on gender, race, ethnicity, age, religion, ability, etc'), (8, '(8) Other victim (specify in comments)'), (9, '(9) Do not know, cannot decide')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='victim_or_survivor',
            field=models.CharField(help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(13) Does the story identify the person as either a victim or survivor?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='about_women',
            field=models.CharField(max_length=1, verbose_name='(16) Is the story about a particular woman or group of women?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='comments',
            field=models.TextField(verbose_name='(N/A) Describe any photographs included in the story and the conclusions you draw from them.', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='equality_rights',
            field=models.CharField(help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(4) Reference to gender equality / human rights legislation/ policy', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='further_analysis',
            field=models.CharField(help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(19) Does this story warrant further analysis?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='inequality_women',
            field=models.PositiveIntegerField(verbose_name='(17) This story clearly highlights issues of inequality between women and men', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='item_number',
            field=models.PositiveIntegerField(help_text='Write in the number that describes the position of the story within the newscast. E.g. the first story in the newscast is item 1; the seventh story is item 7.', verbose_name='(1) Item Number', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='scope',
            field=models.PositiveIntegerField(help_text='Code the widest geographical scope that applies: if the event has both local and national importance, code national.', verbose_name='(3) Scope', choices=[(1, '(1) Local'), (2, '(2) National'), (3, '(3) Sub-Regional'), (4, '(4) Foreign/International')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='stereotypes',
            field=models.PositiveIntegerField(help_text='This story clearly challenges gender stereotypes', verbose_name='(18) Stereotypes', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='topic',
            field=models.PositiveIntegerField(help_text="Choose one topic that best describes how the story is reported. Remember that a single event can be reported in different ways. Within each broad category, we include a code for 'other stories'. Please use these codes only as a <strong>last resort</strong>.", verbose_name='(2) Topic', choices=[(1, '(1) Women politicians, women electoral candidates...'), (2, '(2) Peace, negotiations, treaties'), (3, '(3) Other domestic politics, government, etc.'), (4, '(4) Global partnerships'), (5, '(5) Foreign/international politics, UN, peacekeeping'), (6, '(6) National defence, military spending, internal security, etc.'), (7, '(7) Other stories on politics (specify in comments)'), (8, '(8) Economic policies, strategies, modules, indicators, stock markets, etc'), (9, '(9) Economic crisis, state bailouts of companies, company takeovers and mergers, etc.'), (10, '(10) Poverty, housing, social welfare, aid, etc.'), (11, '(11) Womens participation in economic processes'), (12, '(12) Employment'), (13, '(13) Informal work, street vending, etc.'), (14, '(14) Other labour issues (strikes, trade unions, etc.)'), (15, '(15) Rural economy, agriculture, farming, land rights'), (16, '(16) Consumer issues, consumer protection, fraud...'), (17, '(17) Transport, traffic, roads...'), (18, '(18) Other stories on economy (specify in comments)'), (19, '(19) Science, technology, research, discoveries...'), (20, '(20) Medicine, health, hygiene, safety, (not EBOLA or HIV/AIDS)'), (21, '(21) EBOLA, treatment, response...'), (22, '(22) HIV and AIDS, policy, treatment, etc'), (23, '(23) Other epidemics, viruses, contagions, Influenza, BSE, SARS'), (24, '(24) Birth control, fertility, sterilization, termination...'), (25, '(25) Climate change, global warming'), (26, '(26) Environment, pollution, tourism'), (27, '(27) Other stories on science (specify in comments)'), (28, '(28) Millennium Development Goals (MDGs), Post 2015 agenda, Sustainable Development Goals'), (29, '(29) Family relations, inter-generational conflict, parents'), (30, '(30) Human rights, womens rights, rights of sexual minorities, rights of religious minorities, etc.'), (31, '(31) Religion, culture, tradition, controversies...'), (32, '(32) Migration, refugees, xenophobia, ethnic conflict...'), (33, '(33) Other development issues, sustainability, etc.'), (34, '(34) Education, childcare, nursery, university, literacy'), (35, '(35) Womens movement, activism, demonstrations, etc'), (36, '(36) Changing gender relations (outside the home)'), (37, '(37) Family law, family codes, property law, inheritance...'), (38, '(38) Legal system, judiciary, legislation apart from family'), (39, '(39) Disaster, accident, famine, flood, plane crash, etc.'), (40, '(40) Riots, demonstrations, public disorder, etc.'), (41, '(41) Other stories on social/legal (specify in comments)'), (42, '(42) Non-violent crime, bribery, theft, drugs, corruption'), (43, '(43) Violent crime, murder, abduction, assault, etc.'), (44, '(44) Gender violence based on culture, family, inter-personal relations, feminicide, harassment, rape, sexual assault, trafficking, FGM...'), (45, '(45) Gender violence perpetuated by the State'), (46, '(46) Child abuse, sexual violence against children, neglect'), (47, '(47) War, civil war, terrorism, other state-based violence'), (48, '(48) Other crime/violence (specify in comments)'), (49, '(49) Celebrity news, births, marriages, royalty, etc.'), (50, '(50) Arts, entertainment, leisure, cinema, books, dance'), (51, '(51) Media, (including internet), portrayal of women/men'), (52, '(52) Beauty contests, models, fashion, cosmetic surgery'), (53, '(53) Sports, events, players, facilities, training, funding'), (54, '(54) Other celebrity/arts/media news (specify in comments)'), (55, '(55) Other (only use as a last resort & explain)')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twitterjournalist',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age (person appears)', choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65 years or more')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twitterjournalist',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='Journalists Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='is_photograph',
            field=models.PositiveIntegerField(verbose_name='(5) Is there a photograph of the person in the story?', choices=[(1, '(0) Yes'), (2, '(1) No'), (3, '(2) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='sex',
            field=models.PositiveIntegerField(verbose_name='(4) Sex', choices=[(1, '(1) Female'), (2, '(2) Male'), (3, '(3) Other (transgender, etc.)'), (4, '(4) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='about_women',
            field=models.CharField(max_length=1, verbose_name='(7) Is the tweet about a particular woman or group of women?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='comments',
            field=models.TextField(verbose_name='(TODO should this be here?) Describe any photographs included in the story and the conclusions you draw from them.', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='further_analysis',
            field=models.CharField(help_text="<br><br>A tweet warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(9) Does this tweet warrant further analysis?', choices=[(b'Y', '(1) Yes'), (b'N', '(2) No')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='retweet',
            field=models.PositiveIntegerField(help_text='Only retweets from the same media house can be coded. Do not code retweets from other news providers', verbose_name='(1) Tweet or Retweet', choices=[(1, '(0) Tweet'), (2, '(1) Retweet')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='stereotypes',
            field=models.PositiveIntegerField(help_text='This tweet clearly challenges gender stereotypes', verbose_name='(8) Stereotypes', choices=[(1, '(0) Agree'), (2, '(1) Disagree'), (3, '(2) Neither agree nor disagree'), (4, '(3) Do not know')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='topic',
            field=models.PositiveIntegerField(help_text="Choose one topic that best describes how the story is reported. Remember that a single event can be reported in different ways. Within each broad category, we include a code for 'other stories'. Please use these codes only as a <strong>last resort</strong>.", verbose_name='(2) Topic', choices=[(1, '(1) Women politicians, women electoral candidates...'), (2, '(2) Peace, negotiations, treaties'), (3, '(3) Other domestic politics, government, etc.'), (4, '(4) Global partnerships'), (5, '(5) Foreign/international politics, UN, peacekeeping'), (6, '(6) National defence, military spending, internal security, etc.'), (7, '(7) Other stories on politics (specify in comments)'), (8, '(8) Economic policies, strategies, modules, indicators, stock markets, etc'), (9, '(9) Economic crisis, state bailouts of companies, company takeovers and mergers, etc.'), (10, '(10) Poverty, housing, social welfare, aid, etc.'), (11, '(11) Womens participation in economic processes'), (12, '(12) Employment'), (13, '(13) Informal work, street vending, etc.'), (14, '(14) Other labour issues (strikes, trade unions, etc.)'), (15, '(15) Rural economy, agriculture, farming, land rights'), (16, '(16) Consumer issues, consumer protection, fraud...'), (17, '(17) Transport, traffic, roads...'), (18, '(18) Other stories on economy (specify in comments)'), (19, '(19) Science, technology, research, discoveries...'), (20, '(20) Medicine, health, hygiene, safety, (not EBOLA or HIV/AIDS)'), (21, '(21) EBOLA, treatment, response...'), (22, '(22) HIV and AIDS, policy, treatment, etc'), (23, '(23) Other epidemics, viruses, contagions, Influenza, BSE, SARS'), (24, '(24) Birth control, fertility, sterilization, termination...'), (25, '(25) Climate change, global warming'), (26, '(26) Environment, pollution, tourism'), (27, '(27) Other stories on science (specify in comments)'), (28, '(28) Millennium Development Goals (MDGs), Post 2015 agenda, Sustainable Development Goals'), (29, '(29) Family relations, inter-generational conflict, parents'), (30, '(30) Human rights, womens rights, rights of sexual minorities, rights of religious minorities, etc.'), (31, '(31) Religion, culture, tradition, controversies...'), (32, '(32) Migration, refugees, xenophobia, ethnic conflict...'), (33, '(33) Other development issues, sustainability, etc.'), (34, '(34) Education, childcare, nursery, university, literacy'), (35, '(35) Womens movement, activism, demonstrations, etc'), (36, '(36) Changing gender relations (outside the home)'), (37, '(37) Family law, family codes, property law, inheritance...'), (38, '(38) Legal system, judiciary, legislation apart from family'), (39, '(39) Disaster, accident, famine, flood, plane crash, etc.'), (40, '(40) Riots, demonstrations, public disorder, etc.'), (41, '(41) Other stories on social/legal (specify in comments)'), (42, '(42) Non-violent crime, bribery, theft, drugs, corruption'), (43, '(43) Violent crime, murder, abduction, assault, etc.'), (44, '(44) Gender violence based on culture, family, inter-personal relations, feminicide, harassment, rape, sexual assault, trafficking, FGM...'), (45, '(45) Gender violence perpetuated by the State'), (46, '(46) Child abuse, sexual violence against children, neglect'), (47, '(47) War, civil war, terrorism, other state-based violence'), (48, '(48) Other crime/violence (specify in comments)'), (49, '(49) Celebrity news, births, marriages, royalty, etc.'), (50, '(50) Arts, entertainment, leisure, cinema, books, dance'), (51, '(51) Media, (including internet), portrayal of women/men'), (52, '(52) Beauty contests, models, fashion, cosmetic surgery'), (53, '(53) Sports, events, players, facilities, training, funding'), (54, '(54) Other celebrity/arts/media news (specify in comments)'), (55, '(55) Other (only use as a last resort & explain)')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='url_and_multimedia',
            field=models.TextField(verbose_name='(6) Copy and paste the URL of the tweet. Describe any photographs, images, other multimedia features included in the tweet. Note down the conclusions you draw from the images, audio and video.', blank=True),
            preserve_default=True,
        ),
    ]
