# Generated by Django 2.2.9 on 2020-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_auto_20191218_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewsperson',
            name='family_role',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(16) Family Role Given?'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='is_quoted',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text='<p>A person is <strong>directly quoted</strong> if their own words are printed, e.g. "The war against terror is our first priority" said President Bush.</p><p>If the story paraphrases what the person said, that is not a direct quote, e.g. President Bush said that top priority would be given to fighting the war against terror.</p>', max_length=1, verbose_name='(20) Is the person directly quoted'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(20) Special question 1'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(21) Special question 2'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question 3'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='victim_or_survivor',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(17) Does the story identify the person as either a victim or survivor?'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='about_women',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(7) Is the story about a particular woman or group of women?'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='equality_rights',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(6) Reference to gender equality / human rights legislation/ policy'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='further_analysis',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(26) Does this story warrant further analysis?'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='inequality_women',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(8) This story clearly highlights issues of inequality between women and men'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='offline_presence',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='Offline presence?'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='shared_on_facebook',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text='Has this story been shared by the media house on its Facebook Page?', max_length=1, verbose_name='(5) Shared on Facebook'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='shared_via_twitter',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text='Has this story been shared by the media house via Twitter?\n\n<br>Enter the exact URL of the story into <a href="https://unionmetrics.com/free-tools/twitter-snapshot-report/" target="_blank">https://unionmetrics.com/free-tools/twitter-snapshot-report/</a> - answer yes if the media house\'s name appears in the search results.', max_length=1, verbose_name='(4) Shared via twitter?'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], help_text='This story clearly challenges gender stereotypes', verbose_name='(9) Challenges Stereotypes'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='family_role',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(14) Family Role Given?'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='is_quoted',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text='<p>A person is <strong>directly quoted</strong> if their own words are printed, e.g. "The war against terror is our first priority" said President Bush.</p><p>If the story paraphrases what the person said, that is not a direct quote, e.g. President Bush said that top priority would be given to fighting the war against terror.</p>', max_length=1, verbose_name='(18) Is the person directly quoted'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(20) Special question 1'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(21) Special question 2'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question 3'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='victim_or_survivor',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(15) Does the story identify the person as either a victim or survivor?'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='about_women',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(6) Is the story about a particular woman or group of women?'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='equality_rights',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(5) Reference to gender equality / human rights legislation/ policy'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='further_analysis',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(24) Does this story warrant further analysis?'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='inequality_women',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(7) This story clearly highlights issues of inequality between women and men'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], help_text='This story clearly challenges gender stereotypes', verbose_name='(8) Challenges Stereotypes'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='family_role',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(13) Family Role Given?'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(20) Special question 1'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(21) Special question 2'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question 3'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='victim_or_survivor',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(14) Does the story identify the person as either a victim or survivor?'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='about_women',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(5) Is the story about a particular woman or group of women?'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='equality_rights',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(4) Reference to gender equality / human rights legislation/ policy'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='further_analysis',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(20) Does this story warrant further analysis?'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='inequality_women',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(6) This story clearly highlights issues of inequality between women and men'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], help_text='This story clearly challenges gender stereotypes', verbose_name='(7) Challenges Stereotypes'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='family_role',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Code yes only if the word 'wife', 'husband' etc is actually used to describe the person.", max_length=1, verbose_name='(15) Family Role Given?'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(20) Special question 1'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(21) Special question 2'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question 3'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='victim_or_survivor',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<p>You should code a person as a <strong>victim</strong> either if the word 'victim' is used to describe her/him, or if the story Implies that the person is a victim - e.g. by using language or images that evoke particular emotions such as shock, horror, pity for the person.</p><p>You should code a person as a <strong>survivor</strong> either if the word 'survivor' is used to describe her/him, or if the story implies that the person is a survivor - e.g. by using language or images that evoke particular emotions such as admiration or respect for the person.</p>", max_length=1, verbose_name='(16) Does the story identify the person as either a victim or survivor?'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='about_women',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(5) Is the story about a particular woman or group of women?'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='equality_rights',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(4) Reference to gender equality / human rights legislation/ policy'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='further_analysis',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<br><br>A story warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(22) Does this story warrant further analysis?'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='inequality_women',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(6) This story clearly highlights issues of inequality between women and men'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], help_text='This story clearly challenges gender stereotypes', verbose_name='(7) Challenges Stereotypes'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(14) Special question 1'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(15) Special question 2'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(16) Special question 3'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='about_women',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(4) Is the story about a particular woman or group of women?'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='equality_rights',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="Scan the full news story and code 'Yes' if it quotes or makes reference to any piece of legislation or policy that promotes gender equality or human rights.", max_length=1, verbose_name='(3) Reference to gender equality / human rights legislation/ policy'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='further_analysis',
            field=models.CharField(choices=[('Y', '(1) Yes'), ('N', '(2) No')], help_text="<br><br>A tweet warrants further analysis if it clearly perpetuates or clearly challenges gender stereotypes, if it includes women's opinions in a remarkable way, if it contributes to an understanding of inequalities between women and men, if it mentions or calls attention to women's human rights, etc. Consult the guide for further explanation", max_length=1, verbose_name='(18) Does this tweet warrant further analysis?'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='inequality_women',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(5) This story clearly highlights issues of inequality between women and men'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], help_text='This story clearly challenges gender stereotypes', verbose_name='(6) Challenges Stereotypes'),
        ),
    ]
