# Generated by Django 2.2.9 on 2020-01-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_auto_20200114_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewssheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(9) This story clearly challenges gender stereotypes'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(8) This story clearly challenges gender stereotypes'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(7) This story clearly challenges gender stereotypes'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(7) This story clearly challenges gender stereotypes'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='stereotypes',
            field=models.PositiveIntegerField(choices=[(1, '(1) Agree'), (2, '(2) Disagree')], verbose_name='(6) This story clearly challenges gender stereotypes'),
        ),
    ]
