# Generated by Django 2.2.9 on 2020-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_auto_20200115_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(17) Special question 1'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(18) Special question 2'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(19) Special question 3'),
        ),
    ]
