# Generated by Django 2.2.9 on 2020-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0040_auto_20200120_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question 1'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(23) Special question 2'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(24) Special question 3'),
        ),
    ]
