# Generated by Django 2.2.9 on 2020-02-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0041_auto_20200123_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetnewssheet',
            options={'verbose_name': 'Internet'},
        ),
        migrations.AlterModelOptions(
            name='newspapersheet',
            options={'verbose_name': 'Newspaper'},
        ),
        migrations.AlterModelOptions(
            name='radiosheet',
            options={'verbose_name': 'Radio'},
        ),
        migrations.AlterModelOptions(
            name='televisionsheet',
            options={'verbose_name': 'Television'},
        ),
        migrations.AlterModelOptions(
            name='twittersheet',
            options={'verbose_name': 'Twitter'},
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question (1)'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(23) Special question (2)'),
        ),
        migrations.AlterField(
            model_name='internetnewsperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(24) Special question (3)'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(20) Special question (1)'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(21) Special question (2)'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(22) Special question (3)'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(17) Special question (1)'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(18) Special question (2)'),
        ),
        migrations.AlterField(
            model_name='radioperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(19) Special question (3)'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(19) Special question (1)'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(20) Special question (2)'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(21) Special question (3)'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='special_qn_1',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(14) Special question (1)'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='special_qn_2',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(15) Special question (2)'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='special_qn_3',
            field=models.CharField(blank=True, choices=[('Y', '(1) Yes'), ('N', '(2) No')], max_length=1, verbose_name='(16) Special question (3)'),
        ),
    ]
