# Generated by Django 2.2.9 on 2020-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0044_auto_20200226_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiosheet',
            name='num_female_anchors',
            field=models.PositiveIntegerField(help_text='The anchor (or announcer, or presenter) is the person who introduces the newscast and the individual items within it. <strong>Note: You should only include the anchors/announcers. Do not include reporters or other journalists</strong>', verbose_name='Number of female anchors'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='num_female_anchors',
            field=models.PositiveIntegerField(help_text='The anchor (or announcer, or presenter) is the person who introduces the newscast and the individual items within it. <strong>Note: You should only include the anchors/announcers. Do not include reporters or other journalists</strong>', verbose_name='Number of female anchors'),
        ),
    ]
