# Generated by Django 2.2.15 on 2020-08-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0048_auto_20200820_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewssheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], default=2, help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], default=2, help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], default=2, help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], default=2, help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], default=2, help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
    ]
