# Generated by Django 2.2.15 on 2020-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0049_auto_20200820_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewsperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(13) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(11) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(12) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(10) Age (person appears)'),
        ),
    ]
