# Generated by Django 2.2.16 on 2020-09-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0050_add_created_and_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewsperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(13) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='internetnewssheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='newspaperperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(11) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='televisionperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(12) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
        migrations.AlterField(
            model_name='twitterperson',
            name='age',
            field=models.PositiveIntegerField(choices=[(0, '(0) Do not know'), (1, '(1) 12 and under'), (2, '(2) 13-18'), (3, '(3) 19-34'), (4, '(4) 35-49'), (5, '(5) 50-64'), (6, '(6) 65-79'), (7, '(7) 80 years or more')], verbose_name='(10) Age (person appears)'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='covid19',
            field=models.PositiveIntegerField(choices=[(1, '(1) Yes'), (2, '(2) No')], help_text='Note: For the question below it is important <strong>NOT</strong> to code COVID19-related stories under topic 23 but to choose the most relevant <strong>secondary</strong> topic theme in order to ensure results that can be compared with those from previous GMMPs.', verbose_name='(z) Is this story related to coronavirus Covid-19?'),
        ),
    ]
