# Generated by Django 2.2.16 on 2020-09-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0052_make_fields_nullable_20200907_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetnewssheet',
            name='monitor_mode',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='short', max_length=10),
        ),
        migrations.AddField(
            model_name='newspapersheet',
            name='monitor_mode',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='short', max_length=10),
        ),
        migrations.AddField(
            model_name='radiosheet',
            name='monitor_mode',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='short', max_length=10),
        ),
        migrations.AddField(
            model_name='televisionsheet',
            name='monitor_mode',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='short', max_length=10),
        ),
        migrations.AddField(
            model_name='twittersheet',
            name='monitor_mode',
            field=models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='short', max_length=10),
        ),
    ]
