# Generated by Django 2.2.16 on 2020-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0053_add_monitoring_mode_20200909_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetnewssheet',
            name='monitor_mode',
            field=models.IntegerField(choices=[(1, 'Full monitoring'), (2, 'Short monitoring')], default=1, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='newspapersheet',
            name='monitor_mode',
            field=models.IntegerField(choices=[(1, 'Full monitoring'), (2, 'Short monitoring')], default=1, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='radiosheet',
            name='monitor_mode',
            field=models.IntegerField(choices=[(1, 'Full monitoring'), (2, 'Short monitoring')], default=1, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='televisionsheet',
            name='monitor_mode',
            field=models.IntegerField(choices=[(1, 'Full monitoring'), (2, 'Short monitoring')], default=1, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='twittersheet',
            name='monitor_mode',
            field=models.IntegerField(choices=[(1, 'Full monitoring'), (2, 'Short monitoring')], default=1, verbose_name='Format'),
        ),
    ]
