# Generated by Django 2.2.16 on 2020-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0056_allow_blank_and_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetnewssheet',
            name='monitor_code',
            field=models.CharField(default='', max_length=255, verbose_name='Monitor Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspapersheet',
            name='monitor_code',
            field=models.CharField(default='', max_length=255, verbose_name='Monitor Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiosheet',
            name='monitor_code',
            field=models.CharField(default='', max_length=255, verbose_name='Monitor Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='televisionsheet',
            name='monitor_code',
            field=models.CharField(default='', max_length=255, verbose_name='Monitor Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twittersheet',
            name='monitor_code',
            field=models.CharField(default='', max_length=255, verbose_name='Monitor Code'),
            preserve_default=False,
        ),
    ]
