version: "3"
services:
  db:
    image: postgres:9.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=gmmp
      - POSTGRES_PASSWORD=gmmp
      - POSTGRES_DB=gmmp
      - PGUSER=gmmp
      - PGPASSWORD=gmmp
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://asciicfa:@host.docker.internal:5432/gmmp
      - DJANGO_SECRET_KEY=somethingsecret
      - SITE_URL=http://localhost:8000
      - PGHOST=db
      - PGDATABASE=gmmp
      - PGUSER=gmmp
      - PGPASSWORD=gmmp
      - PYTHONDONTWRITEBYTECODE=True
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True} # For testing deploys
      - GMMP_EMAIL_HOST_PASSWORD=${GMMP_EMAIL_HOST_PASSWORD}
      - GMMP_REPORTS_HISTORICAL_YEAR=${GMMP_REPORTS_HISTORICAL_YEAR:-2010}
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 # https://stackoverflow.com/a/51643134
    command: [
        "/cmd.sh",
        "--log-level=debug",
        "--reload",
        "gmmp.wsgi:application",
      ]

volumes:
  logvolume01: {}
