from collections import OrderedDict

WS_INFO = {
    'ws_01': {
        'name': '1',
        'title': 'Participating Countries',
        'desc': 'Breakdown of all media by region',
        'reports': ['global'],
    },
    'ws_02': {
        'name': '2',
        'title': 'Participating Countries in each Region',
        'desc': 'Breakdown of all media by country',
        'reports': ['global', 'region'],
    },
    'ws_04': {
        'name': '4',
        'title': 'Topics in the news by region',
        'desc': 'Breakdown of major news topics by region by medium',
        'reports': ['global', 'region'],
    },
    'ws_05': {
        'name': '5',
        'title': 'Summary of women in the news, by GMMP year',
        'desc': 'Overall presence of women in news',
        'reports': ['global', 'region', 'country'],
    },
    'ws_06': {
        'name': '6',
        'title': 'Breakdown of women in the news in major topics by region',
        'desc': 'Women in the news (sources) in major news topics by region ',
        'reports': ['global', 'region', 'country'],
    },
    'ws_07': {
        'name': '7',
        'title': 'Women in the news (sources) by medium',
        'desc': 'Breakdown by sex of all mediums',
        'reports': ['global', 'region', 'country'],
    },
    'ws_08': {
        'name': '8',
        'title': 'Sex of news subjects (sources) inlocal,national,sub-regional/regional, foreign/intnl news',
        'desc': 'Breakdown by sex local,national,sub-regional/regional, intnl news',
        'reports': ['global', 'region', 'country'],
    },
    'ws_09': {
        'name': '9',
        'title': 'Sex of news subjects in different story topics',
        'desc': 'Breakdown of topic by sex',
        'reports': ['global', 'region'],
    },
    'ws_10': {
        'name': '10',
        'title': 'Space allocated to major topics in Newspapers',
        'desc': 'Breakdown by major topic by space (q.4) in newspapers',
        'reports': ['global', 'region', 'country'],
    },
    'ws_11': {
        'name': '11',
        'title': 'Stories making reference to issues of gender equality/inequality, legislation, policy by major topic',
        'desc': 'Breakdown by major topic by reference to gender equality/human rights/policy',
        'reports': ['global', 'region', 'country'],
    },
    'ws_12': {
        'name': '12',
        'title': 'Stories making reference to issues of gender equality/inequality, legislation, policy by region',
        'desc': 'Breakdown by major topic by region by reference to gender equality/human rights/policy',
        'reports': ['global', 'region'],
    },
    'ws_13': {
        'name': '13',
        'title': 'Stories making reference to issues of gender equality/inequality, legislation, policy by sex of reporter',
        'desc': 'B.down by major topic by sex of reporter by reference to gender equality/human rights/policy',
        'reports': ['global', 'region',  'country'],
    },
    'ws_14': {
        'name': '14',
        'title': 'Position or occupation of news sources, by sex',
        'desc': 'Breakdown of new sources by occupation and sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_15': {
        'name': '15',
        'title': 'News subject''s Function in news story, by sex',
        'desc': 'Breakdown by sex and function',
        'reports': ['global', 'region', 'country'],
    },
    'ws_16': {
        'name': '16',
        'title': 'Function of news subjects by sex - by occupation',
        'desc': 'Breakdown of  Function of news subjects by sex - by occupation',
        'reports': ['global', 'region', 'country'],
    },
    'ws_17': {
        'name': '17',
        'title': 'Function of news subjects by sex - by age',
        'desc': 'Breakdown of  Function of news subjects by sex - by age',
        'reports': ['global', 'region', 'country'],
    },
    'ws_18': {
        'name': '18',
        'title': 'Age of news subjects by print, by sex',
        'desc': 'B.down of  Age of news subjects by print, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_19': {
        'name': '19',
        'title': 'Age of news subjects by broadcast, by sex',
        'desc': 'B.down of  Age of news subjects by broadcast, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_20': {
        'name': '20',
        'title': 'Functions (top 5) and Occupations by sex of news subject',
        'desc': 'B.down of  news subjects\' functions (top 5) and occupations by sex of news subject',
        'reports': ['global', 'region', 'country'],
    },
    'ws_21': {
        'name': '21',
        'title': 'Breakdown by victim type by sex',
        'desc': 'News Subjects who are portrayed as victims, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_23': {
        'name': '23',
        'title': 'Breakdown by survivor type by sex',
        'desc': 'News subjects who are portrayed as survivors, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_24': {
        'name': '24',
        'title': 'Breakdown by family status, by sex.',
        'desc': 'News subjects who are identified by family status, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_25': {
        'name': '25',
        'title': 'B.down by sex of subject, family status, by sex of reporter',
        'desc': 'News subjects who are identified by family status, by sex of news subject, by sex of reporter',
        'reports': ['global', 'region', 'country'],
    },
    'ws_26': {
        'name': '26',
        'title': 'Breakdown of  news subjects quoted, by sex',
        'desc': 'News subjects quoted, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_27': {
        'name': '27',
        'title': 'Breakdown of News subjects photographed, by sex',
        'desc': 'News subjects photographed, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_28': {
        'name': '28',
        'title': 'Breakdown of total female reporters & presenters by region by medium ',
        'desc': 'Female reporters, announcers and presenters all media, by region',
        'reports': ['global', 'region', 'country'],
    },
    'ws_29': {
        'name': '29',
        'title': 'Breakdown of female reporters in domestic & foreign stories, by region',
        'desc': 'Reporters in domestic & foreign stories (scope) , by region, by sex of reporter region',
        'reports': ['global', 'region', 'country'],
    },
    'ws_30': {
        'name': '30',
        'title': 'Breakdown of female reporters, by major topic, by region',
        'desc': 'Reporters, by sex on major topics, by region',
        'reports': ['global', 'region', 'country'],
    },
    'ws_31': {
        'name': '31',
        'title': 'Breakdown of Reporters, by sex on different topics - Detail',
        'desc': 'Rporters, by sex on different topics - Detail',
        'reports': ['global'],
    },
    'ws_32': {
        'name': '32',
        'title': 'Topics in the news - Detail by medium for female reporters',
        'desc': 'Topics in the news - Detail by medium for female reporters',
        'reports': ['global'],
    },
    'ws_34': {
        'name': '34',
        'title': 'Breakdown of News Subject(sex of source) selection by female & male reporters',
        'desc': 'Selection of News Subject(sex of source) by female & male reporters',
        'reports': ['global', 'region', 'country'],
    },
    'ws_35': {
        'name': '35',
        'title': 'Breakdown of television Announcers & Reporters, by age, by sex',
        'desc': 'Age of television Announcers & Reporters, by sex',
        'reports': ['global', 'region', 'country'],
    },
    'ws_36': {
        'name': '36',
        'title': 'Breakdown of Stories with Women as central focus (is this story about a particular woman or women) by sex of reporter',
        'desc': 'Stories with Women as central focus  by sex of reporter',
        'reports': ['global', 'region', 'country'],
    },
    'ws_38': {
        'name': '38',
        'title': 'Breakdown of Stories with Women as a central Focus by major topic',
        'desc': 'Stories with Women as a central Focus by major topic',
        'reports': ['global', 'region', 'country'],
    },
    'ws_39': {
        'name': '39',
        'title': 'Breakdown of Stories with Women as a central Focus by minor topic',
        'desc': 'Stories with Women as a central Focus by minor topic',
        'reports': ['global'],
    },
    'ws_40': {
        'name': '40',
        'title': 'Breakdown of Stories with Women as a central Focus by topic and region',
        'desc': 'Stories with Women as a central Focus by topic and region',
        'reports': ['global'],
    },
    'ws_41': {
        'name': '41',
        'title': 'Breakdown of Stories where issues of gender equality/inequality are raised by topic',
        'desc': 'Stories where issues of gender equality/inequality are raised by topic',
        'reports': ['global', 'region', 'country'],
    },
    'ws_42': {
        'name': '42',
        'title': 'Breakdown of Stories where issues of gender equality/inequality are raised by region',
        'desc': 'Stories where issues of gender equality/inequality are raised by region',
        'reports': ['global'],
    },
    'ws_43': {
        'name': '43',
        'title': 'Breakdown of Stories where issues of gender equality/inequality are raised by sex of reporter',
        'desc': 'Stories where issues of gender equality/inequality are raised by sex of reporter',
        'reports': ['global', 'region', 'country'],
    },
    'ws_44': {
        'name': '44',
        'title': 'Stories where issues of gender equality/inequality are raised by sex of reporter and by region',
        'desc': 'Stories where issues of gender equality/inequality are raised by sex of reporter and by region',
        'reports': ['global', 'region'],
    },
    'ws_45': {
        'name': '45',
        'title': 'Stories where issues of gender equality/inequality are raised by sex of \'people in the news\' and by region',
        'desc': 'Stories where issues of gender equality/inequality are raised by sex of \'people in the news\' and by region',
        'reports': ['global', 'region'],
    },
    'ws_46': {
        'name': '46',
        'title': 'Story clearly challenges gender stereotypes by region by major news topic',
        'desc': 'Stories where stereotypes are challenged/ supported by news topic',
        'reports': ['global'],
    },
    'ws_47': {
        'name': '47',
        'title': 'Story clearly challenges gender stereotypes by major topic',
        'desc': 'Stories where stereotypes are challenged/ supported by topic',
        'reports': ['global', 'region', 'country'],
    },
    'ws_48': {
        'name': '48',
        'title': 'Story clearly challenges gender stereotypes by sex of rep',
        'desc': 'Stories where stereotypes are challenged/ supported by gender of rep',
        'reports': ['global', 'region', 'country'],
    },
    'ws_53': {
        'name': '53',
        'title': 'Internet - Female reporters in main stories',
        'desc': 'Internet - Female reporters in main stories',
        'reports': ['global', 'region', 'country']
    },
    'ws_54': {
        'name': '54',
        'title': 'Internet - Overall presence of women',
        'desc': 'Internet - Overall presence of women',
        'reports': ['global', 'region', 'country']
    },
    'ws_55': {
        'name': '55',
        'title': 'Internet - Occupation of Female news subjects',
        'desc': 'Internet - Occupation of Female news subjects',
        'reports': ['global'],
    },
    'ws_56': {
        'name': '56',
        'title': 'Internet - Functions of news subjects',
        'desc': 'Internet - Functions of news subjects',
        'reports': ['global', 'region', 'country'],
    },
    'ws_57': {
        'name': '57',
        'title': 'Internet - News subjects who are identified by family status',
        'desc': 'Internet - News subjects who are identified by family status',
        'reports': ['global', 'country'],
    },
    'ws_58': {
        'name': '58',
        'title': 'Internet - News subjects in multimedia web components',
        'desc': 'Internet - News subjects in multimedia web components',
        'reports': ['global', 'country'],
    },
    'ws_59': {
        'name': '59',
        'title': 'Internet - Selection of News Subjects',
        'desc': 'Internet - Selection of News Subjects',
        'reports': ['global', 'country'],
    },
    'ws_60': {
        'name': '60',
        'title': 'Internet - Age of news subjects',
        'desc': 'Internet - Age of news subjects',
        'reports': ['global', 'country'],
    },
    'ws_61': {
        'name': '61',
        'title': 'Internet - News subjects who are directly quoted',
        'desc': 'Internet - News subjects who are directly quoted',
        'reports': ['global', 'country'],
    },
    'ws_62': {
        'name': '62',
        'title': 'Internet - Stories where issues of gender equality/inequality are raised by topic',
        'desc': 'Internet - Stories where issues of gender equality/inequality are raised by topic',
        'reports': ['global', 'region', 'country'],
    },
    'ws_63': {
        'name': '63',
        'title': 'Internet -Stories where stereotypes are clearly challenged',
        'desc': 'Internet -Stories where stereotypes are clearly challenged',
        'reports': ['global', 'region', 'country'],
    },
    'ws_64': {
        'name': '64',
        'title': 'Internet -Stories with Women as a central Focus',
        'desc': 'Internet -Stories with Women as a central Focus',
        'reports': ['global', 'region', 'country'],
    },
    'ws_65': {
        'name': '65',
        'title': 'Twitter - Original tweet or retweet',
        'desc': 'Twitter - Original tweet or retweet',
        'reports': ['global', 'region', 'country'],
    },
    'ws_66': {
        'name': '66',
        'title': 'Twitter - Overall presence of women',
        'desc': 'Twitter - Overall presence of women',
        'reports': ['global', 'region', 'country'],
    },
    'ws_67': {
        'name': '67',
        'title': 'Twitter - Female reporters & journalists',
        'desc': 'Twitter - Female reporters & journalists',
        'reports': ['global', 'region', 'country'],
    },
    'ws_68': {
        'name': '68',
        'title': 'Twitter - Women\'s centrality',
        'desc': 'Twitter - Women\'s centrality',
        'reports': ['global', 'region', 'country'],
    },
    'ws_69': {
        'name': '69',
        'title': 'Twitter - Challenging Stereotypes',
        'desc': 'Twitter - Challenging Stereotypes',
        'reports': ['global', 'region', 'country'],
    },
    'ws_76': {
        'name': '76',
        'title': 'Key themes, challenging stereotypes',
        'desc': 'Key themes, challenging stereotypes',
        'reports': ['global', 'region', 'country'],
    },
    'ws_77': {
        'name': '77',
        'title': 'Key themes, reference to gender equality/HR policies',
        'desc': 'Key themes, reference to gender equality/HR policies',
        'reports': ['global', 'region', 'country'],
    },
    'ws_78': {
        'name': '78',
        'title': 'Key themes, portrayal as victims',
        'desc': 'Key themes, portrayal as victims',
        'reports': ['global', 'region', 'country'],
    },
    'ws_79': {
        'name': '79',
        'title': 'Key themes, portrayal as survivors',
        'desc': 'Key themes, portrayal as survivors',
        'reports': ['global', 'region', 'country'],
    },
}


REGION_COUNTRY_MAP = {
    'Africa': [
        'BJ', 'BW', 'BF', 'BI', 'CM', 'CV', 'CF', 'TD', 'KM', 'CD', 'CG', 'GQ',
        'ET', 'GA', 'GM', 'GH', 'GW', 'GN', 'CI', 'KE', 'LS', 'LR', 'MG', 'MW',
        'ML', 'MR', 'MU', 'NA', 'NE', 'NG', 'SN', 'SL', 'SO', 'ZA', 'SD', 'SS',
        'SZ', 'TZ', 'TG', 'UG', 'ZM', 'ZW'],
    'Asia': [
        'AF', 'BD', 'BT', 'CN', 'IN', 'ID', 'JP', 'KG', 'MY', 'MN', 'NP', 'PK', 'PH',
        'KR', 'TW', 'VU', 'VN'],
    'Carribean': [
        'AG', 'BS', 'BB', 'BZ', 'CU', 'DO', 'GD', 'GY', 'HT', 'JM', 'LC', 'VC',
        'SR', 'TT'],
    'Europe': [
        'AL', 'AM', 'AT', 'BY', 'BE', 'BA', 'BG', 'HR', 'DK', 'EE', 'FI', 'FR',
        'GE', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'KZ', 'LU', 'MK', 'MT', 'MD',
        'ME', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SK', 'SI', 'ES', 'SE', 'CH',
        'TR', 'GB'],
    'Latin America': [
        'AR', 'BO', 'BR', 'CL', 'CO', 'CR', 'EC', 'SV', 'GT', 'MX', 'NI', 'PY',
        'PE', 'PR', 'UY', 'VE'],
    'Middle East': [
        'CY', 'EG', 'IL', 'LB', 'MA', 'PS', 'TN'],
    'North America': [
        'CA', 'US'],
    'Pacific Islands': [
        'AU', 'FJ', 'NZ', 'WS', 'SB', 'TO']}

# TOPIC_GROUPS =  {
#     1: ['(1) Women politicians, women electoral candidates...',
#         '(2) Peace, negotiations, treaties',
#         '(3) Other domestic politics, government, etc.',
#         '(4) Global partnerships',
#         '(5) Foreign/international politics, UN, peacekeeping',
#         '(6) National defence, military spending, internal security, etc.',
#         '(7) Other stories on politics (specify in comments)',
#         '(8) Economic policies, strategies, modules, indicators, stock markets, etc',
#         '(9) Economic crisis, state bailouts of companies, company takeovers and mergers, etc.'],
#     2: ['(10) Poverty, housing, social welfare, aid, etc.',
#         '(11) Womens participation in economic processes',
#         '(12) Employment',
#         '(14) Other labour issues (strikes, trade unions, etc.)',
#         '(15) Rural economy, agriculture, farming, land rights',
#         '(16) Consumer issues, consumer protection, fraud...',
#         '(17) Transport, traffic, roads...',
#         '(18) Other stories on economy (specify in comments)',
#         '(13) Informal work, street vending, etc.'],
#     3: ['(19) Science, technology, research, discoveries...',
#         '(20) Medicine, health, hygiene, safety, (not EBOLA or HIV/AIDS)',
#         '(21) EBOLA, treatment, response...',
#         '(23) Other epidemics, viruses, contagions, Influenza, BSE, SARS',
#         '(24) Birth control, fertility, sterilization, termination...',
#         '(25) Climate change, global warming',
#         '(26) Environment, pollution, tourism',
#         '(27) Other stories on science (specify in comments)',
#         '(22) HIV and AIDS, policy, treatment, etc'],
#     4: ['(29) Family relations, inter-generational conflict, parents',
#         '(30) Human rights, womens rights, rights of sexual minorities, rights of religious minorities, etc.',
#         '(31) Religion, culture, tradition, controversies...',
#         '(32) Migration, refugees, xenophobia, ethnic conflict...',
#         '(33) Other development issues, sustainability, etc.',
#         '(34) Education, childcare, nursery, university, literacy',
#         '(35) Womens movement, activism, demonstrations, etc',
#         '(37) Family law, family codes, property law, inheritance...',
#         '(38) Legal system, judiciary, legislation apart from family',
#         '(39) Disaster, accident, famine, flood, plane crash, etc.',
#         '(40) Riots, demonstrations, public disorder, etc.',
#         '(41) Other stories on social/legal (specify in comments)',
#         '(28) Millennium Development Goals (MDGs), Post 2015 agenda, Sustainable Development Goals'],
#     5: ['(42) Non-violent crime, bribery, theft, drugs, corruption',
#         '(43) Violent crime, murder, abduction, assault, etc.',
#         '(44) Gender violence based on culture, family, inter-personal relations, feminicide, harassment, rape, sexual assault, trafficking, FGM...',
#         '(46) Child abuse, sexual violence against children, neglect',
#         '(47) War, civil war, terrorism, other state-based violence',
#         '(48) Other crime/violence (specify in comments)'],
#     6: ['(49) Celebrity news, births, marriages, royalty, etc.',
#         '(50) Arts, entertainment, leisure, cinema, books, dance',
#         '(51) Media, (including internet), portrayal of women/men',
#         '(53) Sports, events, players, facilities, training, funding',
#         '(54) Other celebrity/arts/media news (specify in comments)'],
#     7: ['(55) Other (only use as a last resort & explain)']
# }


GROUP_TOPICS_MAP = OrderedDict([
    ('1', [1, 2, 3, 4, 5, 6, 7, 8, 9]),
    ('2', [10, 11, 12, 13, 14, 15, 16, 17, 18]),
    ('3', [19, 20, 21, 22, 23, 24, 25, 26, 27]),
    ('4', [28, 29, 30, 31, 32, 33, 34, 35, 37, 38, 39, 40, 41]),
    ('5', [42, 43, 44, 46, 48]),
    ('6', [49, 50, 51, 53, 54]),
    ('7', [55])
])

TOPIC_GROUPS = {
    1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1,
    10: 2, 11: 2, 12: 2, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 2,
    19: 3, 20: 3, 21: 3, 22: 3, 23: 3, 24: 3, 25: 3, 26: 3, 27: 3,
    28: 4, 29: 4, 30: 4, 31: 4, 32: 4, 33: 4, 34: 4, 35: 4, 36: 4, 37: 4, 38: 4, 39: 4, 40: 4, 41: 4,
    42: 5, 43: 5, 44: 5, 45: 5, 46: 5, 47: 5, 48: 5,
    49: 6, 50: 6, 51: 6, 52: 6, 53: 6, 54: 6,
    55: 7
}

MAJOR_TOPICS = (
    (1, 'Politics and Government'),
    (2, 'Economy'),
    (3, 'Science and Health'),
    (4, 'Social and Legal'),
    (5, 'Crime and Violence'),
    (6, 'Celebrity, Arts and Media, Sports'),
    (7, 'Other')
)


FORMATS = {
    'heading': {
        'font_name': 'Arial',
        'bold': True,
        'font_size': '10'
    },

    'col_heading': {
        'font_name': 'Arial',
        'font_size': '10',
        'align': 'center',
        'bg_color': '#99CCFF',
        'border': 1
    },
    'col_heading_def': {
        'font_name': 'Arial',
        'font_size': '10',
        'align': 'center',
        'bg_color': '#99CCFF'
    },
    'sec_col_heading': {
        'font_name': 'Arial',
        'font_size': '10',
        'align': 'center',
        'bg_color': '#CCFFFF',
        'border': 1
    },
    'sec_col_heading_def': {
        'font_name': 'Arial',
        'font_size': '10',
        'align': 'center',
        'bg_color': '#CCFFFF'
    },
    'label': {
        'font_name': 'Arial',
        'font_size': '10'
    },
    'N': {
        'font_name': 'Arial',
        'font_size': '10',
        'font_color': '#3737FF',
    },
    'P': {
        'font_name': 'Arial',
        'font_size': '10',
        'font_color': '#3737FF',
        'num_format': 9
    }
}


COUNTRY_WEIGHTINGS = {
   u'AF': {'Internet': '0.37',
            'Print': '0.33',
            'Radio': '0.93',
            'Region': u'Asia',
            'Television': '0.93'},
    u'AG': {'Internet': '0.08',
            'Print': '0.68',
            'Radio': '0.05',
            'Region': u'Carribean',
            'Television': '0.05'},
    u'AL': {'Internet': '0.36',
            'Print': '1.02',
            'Radio': '0.30',
            'Region': u'Europe',
            'Television': '0.30'},
    u'AM': {'Internet': '0.31',
            'Print': '1.02',
            'Radio': '0.29',
            'Region': u'Europe',
            'Television': '0.29'},
    u'AR': {'Internet': '1.34',
            'Print': '0.74',
            'Radio': '1.07',
            'Region': u'Latin America',
            'Television': '1.07'},
    u'AT': {'Internet': '0.72',
            'Print': '0.58',
            'Radio': '0.48',
            'Region': u'Europe',
            'Television': '0.48'},
    u'AU': {'Internet': '1.23',
            'Print': '0.98',
            'Radio': '0.81',
            'Region': u'Pacific Islands',
            'Television': '0.81'},
    u'BA': {'Internet': '0.43',
            'Print': '0.68',
            'Radio': '0.32',
            'Region': u'Europe',
            'Television': '0.32'},
    u'BB': {'Internet': '0.13',
            'Print': '0.13',
            'Radio': '0.09',
            'Region': u'Carribean',
            'Television': '0.09'},
    u'BD': {'Internet': '0.88',
            'Print': '3.63',
            'Radio': '2.09',
            'Region': u'Asia',
            'Television': '2.09'},
    u'BE': {'Internet': '0.82',
            'Print': '0.70',
            'Radio': '0.55',
            'Region': u'Europe',
            'Television': '0.55'},
    u'BF': {'Internet': '0.23',
            'Print': '0.10',
            'Radio': '0.69',
            'Region': u'Africa',
            'Television': '0.69'},
    u'BG': {'Internet': '0.54',
            'Print': '0.41',
            'Radio': '0.44',
            'Region': u'Europe',
            'Television': '0.44'},
    u'BI': {'Internet': '0.10',
            'Print': '0.10',
            'Radio': '0.54',
            'Region': u'Africa',
            'Television': '0.54'},
    u'BJ': {'Internet': '0.18',
            'Print': '0.03',
            'Radio': '0.54',
            'Region': u'Africa',
            'Television': '0.54'},
    u'BO': {'Internet': '0.53',
            'Print': '0.42',
            'Radio': '0.55',
            'Region': u'Latin America',
            'Television': '0.55'},
    u'BR': {'Internet': '2.78',
            'Print': '1.64',
            'Radio': '2.35',
            'Region': u'Latin America',
            'Television': '2.35'},
    u'BS': {'Internet': '0.15',
            'Print': '0.18',
            'Radio': '0.10',
            'Region': u'Carribean',
            'Television': '0.10'},
    u'BT': {'Internet': '0.12',
            'Print': '0.68',
            'Radio': '0.14',
            'Region': u'Asia',
            'Television': '0.14'},
    u'BW': {'Internet': '0.14',
            'Print': '0.18',
            'Radio': '0.24',
            'Region': u'Africa',
            'Television': '0.24'},
    u'BY': {'Internet': '0.59',
            'Print': '0.47',
            'Radio': '0.51',
            'Region': u'Europe',
            'Television': '0.51'},
    u'BZ': {'Internet': '0.08',
            'Print': '0.68',
            'Radio': '0.10',
            'Region': u'Carribean',
            'Television': '0.10'},
    u'CA': {'Internet': '1.54',
            'Print': '1.31',
            'Radio': '0.99',
            'Region': u'North America',
            'Television': '0.99'},
    u'CD': {'Internet': '0.08',
            'Print': '0.28',
            'Radio': '0.35',
            'Region': u'Africa',
            'Television': '0.35'},
    u'CF': {'Internet': '0.11',
            'Print': '0.68',
            'Radio': '0.36',
            'Region': u'Africa',
            'Television': '0.36'},
    u'CG': {'Internet': '0.33',
            'Print': '0.11',
            'Radio': '0.36',
            'Region': u'Africa',
            'Television': '0.36'},
    u'CH': {'Internet': '0.72',
            'Print': '0.94',
            'Radio': '0.47',
            'Region': u'Europe',
            'Television': '0.47'},
    u'CI': {'Internet': '0.73',
            'Print': '1.02',
            'Radio': '0.79',
            'Region': u'Africa',
            'Television': '0.79'},
    u'CL': {'Internet': '0.92',
            'Print': '0.37',
            'Radio': '0.70',
            'Region': u'Latin America',
            'Television': '0.70'},
    u'CM': {'Internet': '0.33',
            'Print': '0.17',
            'Radio': '0.79',
            'Region': u'Africa',
            'Television': '0.79'},
    u'CN': {'Internet': '6.79',
            'Print': '6.23',
            'Radio': '6.18',
            'Region': u'Asia',
            'Television': '6.18'},
    u'CO': {'Internet': '1.36',
            'Print': '0.66',
            'Radio': '1.16',
            'Region': u'Latin America',
            'Television': '1.16'},
    u'CR': {'Internet': '0.42',
            'Print': '0.34',
            'Radio': '0.37',
            'Region': u'Latin America',
            'Television': '0.37'},
    u'CU': {'Internet': '0.47',
            'Print': '0.12',
            'Radio': '0.56',
            'Region': u'Carribean',
            'Television': '0.56'},
    u'CV': {'Internet': '0.12',
            'Print': '0.18',
            'Radio': '0.12',
            'Region': u'Africa',
            'Television': '0.12'},
    u'CY': {'Internet': '0.23',
            'Print': '0.13',
            'Radio': '0.18',
            'Region': u'Middle East',
            'Television': '0.18'},
    u'DE': {'Internet': '2.27',
            'Print': '2.50',
            'Radio': '1.51',
            'Region': u'Europe',
            'Television': '1.51'},
    u'DK': {'Internet': '0.50',
            'Print': '0.74',
            'Radio': '0.39',
            'Region': u'Europe',
            'Television': '0.39'},
    u'DO': {'Internet': '0.60',
            'Print': '0.68',
            'Radio': '0.54',
            'Region': u'Carribean',
            'Television': '0.54'},
    u'EC': {'Internet': '0.66',
            'Print': '0.72',
            'Radio': '0.66',
            'Region': u'Latin America',
            'Television': '0.66'},
    u'EE': {'Internet': '0.27',
            'Print': '0.27',
            'Radio': '0.19',
            'Region': u'Europe',
            'Television': '0.19'},
    u'EG': {'Internet': '1.70',
            'Print': '1.43',
            'Radio': '1.51',
            'Region': u'Middle East',
            'Television': '1.51'},
    u'ES': {'Internet': '1.59',
            'Print': '1.35',
            'Radio': '1.14',
            'Region': u'Europe',
            'Television': '1.14'},
    u'ET': {'Internet': '0.34',
            'Print': '0.39',
            'Radio': '1.63',
            'Region': u'Africa',
            'Television': '1.63'},
    u'FI': {'Internet': '0.61',
            'Print': '0.03',
            'Radio': '0.39',
            'Region': u'Europe',
            'Television': '0.39'},
    u'FJ': {'Internet': '0.15',
            'Print': '0.12',
            'Radio': '0.16',
            'Region': u'Pacific Islands',
            'Television': '0.16'},
    u'FR': {'Internet': '1.99',
            'Print': '1.69',
            'Radio': '1.33',
            'Region': u'Europe',
            'Television': '1.33'},
    u'GA': {'Internet': '0.11',
            'Print': '0.58',
            'Radio': '0.22',
            'Region': u'Africa',
            'Television': '0.22'},
    u'GB': {'Internet': '2.02',
            'Print': '2.23',
            'Radio': '1.32',
            'Region': u'Europe',
            'Television': '1.32'},
    u'GD': {'Internet': '0.06',
            'Print': '0.68',
            'Radio': '0.05',
            'Region': u'Carribean',
            'Television': '0.05'},
    u'GE': {'Internet': '0.40',
            'Print': '1.02',
            'Radio': '0.34',
            'Region': u'Europe',
            'Television': '0.34'},
    u'GH': {'Internet': '0.61',
            'Print': '0.39',
            'Radio': '0.85',
            'Region': u'Africa',
            'Television': '0.85'},
    u'GM': {'Internet': '0.14',
            'Print': '0.04',
            'Radio': '0.23',
            'Region': u'Africa',
            'Television': '0.23'},
    u'GN': {'Internet': '0.68',
            'Print': '1.67',
            'Radio': '0.56',
            'Region': u'Africa',
            'Television': '0.56'},
    u'GQ': {'Internet': '0.09',
            'Print': '0.68',
            'Radio': '0.15',
            'Region': u'Africa',
            'Television': '0.15'},
    u'GR': {'Internet': '0.68',
            'Print': '0.44',
            'Radio': '0.55',
            'Region': u'Europe',
            'Television': '0.55'},
    u'GT': {'Internet': '0.44',
            'Print': '0.38',
            'Radio': '0.66',
            'Region': u'Latin America',
            'Television': '0.66'},
    u'GW': {'Internet': '0.06',
            'Print': '0.68',
            'Radio': '0.22',
            'Region': u'Africa',
            'Television': '0.22'},
    u'GY': {'Internet': '0.15',
            'Print': '0.15',
            'Radio': '0.15',
            'Region': u'Carribean',
            'Television': '0.15'},
    u'HR': {'Internet': '0.45',
            'Print': '0.41',
            'Radio': '0.34',
            'Region': u'Europe',
            'Television': '0.34'},
    u'HT': {'Internet': '0.30',
            'Print': '0.17',
            'Radio': '0.54',
            'Region': u'Carribean',
            'Television': '0.54'},
    u'HU': {'Internet': '0.73',
            'Print': '0.68',
            'Radio': '0.52',
            'Region': u'Europe',
            'Television': '0.52'},
    u'IE': {'Internet': '0.52',
            'Print': '0.18',
            'Radio': '0.36',
            'Region': u'Europe',
            'Television': '0.36'},
    u'IL': {'Internet': '0.65',
            'Print': '0.89',
            'Radio': '0.46',
            'Region': u'Middle East',
            'Television': '0.46'},
    u'IN': {'Internet': '4.18',
            'Print': '5.72',
            'Radio': '5.90',
            'Region': u'Asia',
            'Television': '5.90'},
    u'IS': {'Internet': '0.15',
            'Print': '0.18',
            'Radio': '0.10',
            'Region': u'Europe',
            'Television': '0.10'},
    u'IT': {'Internet': '1.62',
            'Print': '1.51',
            'Radio': '1.29',
            'Region': u'Europe',
            'Television': '1.29'},
    u'JM': {'Internet': '0.32',
            'Print': '0.27',
            'Radio': '0.28',
            'Region': u'Carribean',
            'Television': '0.28'},
    u'JP': {'Internet': '2.80',
            'Print': '5.27',
            'Radio': '1.87',
            'Region': u'Asia',
            'Television': '1.87'},
    u'KE': {'Internet': '1.10',
            'Print': '0.44',
            'Radio': '1.12',
            'Region': u'Africa',
            'Television': '1.12'},
    u'KG': {'Internet': '0.31',
            'Print': '0.05',
            'Radio': '0.39',
            'Region': u'Asia',
            'Television': '0.39'},
    u'KM': {'Internet': '0.06',
            'Print': '0.68',
            'Radio': '0.14',
            'Region': u'Africa',
            'Television': '0.14'},
    u'KR': {'Internet': '1.80',
            'Print': '1.67',
            'Radio': '1.17',
            'Region': u'Asia',
            'Television': '1.17'},
    u'KZ': {'Internet': '0.84',
            'Print': '0.58',
            'Radio': '0.68',
            'Region': u'Europe',
            'Television': '0.68'},
    u'LB': {'Internet': '0.49',
            'Print': '0.30',
            'Radio': '0.37',
            'Region': u'Middle East',
            'Television': '0.37'},
    u'LC': {'Internet': '0.06',
            'Print': '0.18',
            'Radio': '0.07',
            'Region': u'Carribean',
            'Television': '0.07'},
    u'LR': {'Internet': '0.12',
            'Print': '0.13',
            'Radio': '0.35',
            'Region': u'Africa',
            'Television': '0.35'},
    u'LS': {'Internet': '0.09',
            'Print': '0.08',
            'Radio': '0.24',
            'Region': u'Africa',
            'Television': '0.24'},
    u'LU': {'Internet': '0.19',
            'Print': '0.18',
            'Radio': '0.12',
            'Region': u'Europe',
            'Television': '0.12'},
    u'MA': {'Internet': '1.20',
            'Print': '0.38',
            'Radio': '0.96',
            'Region': u'Middle East',
            'Television': '0.96'},
    u'MD': {'Internet': '0.33',
            'Print': '0.16',
            'Radio': '0.31',
            'Region': u'Europe',
            'Television': '0.31'},
    u'ME': {'Internet': '0.16',
            'Print': '0.00',
            'Radio': '0.13',
            'Region': u'Europe',
            'Television': '0.13'},
    u'MG': {'Internet': '1.11',
            'Print': '0.19',
            'Radio': '0.80',
            'Region': u'Africa',
            'Television': '0.80'},
    u'MK': {'Internet': '0.22',
            'Print': '0.58',
            'Radio': '0.24',
            'Region': u'Europe',
            'Television': '0.24'},
    u'ML': {'Internet': '0.92',
            'Print': '0.68',
            'Radio': '0.66',
            'Region': u'Africa',
            'Television': '0.66'},
    u'MN': {'Internet': '0.19',
            'Print': '0.14',
            'Radio': '0.28',
            'Region': u'Asia',
            'Television': '0.28'},
    u'MR': {'Internet': '0.18',
            'Print': '0.68',
            'Radio': '0.33',
            'Region': u'Africa',
            'Television': '0.33'},
    u'MT': {'Internet': '0.11',
            'Print': '0.13',
            'Radio': '0.11',
            'Region': u'Europe',
            'Television': '0.11'},
    u'MU': {'Internet': '0.07',
            'Print': '0.62',
            'Radio': '0.19',
            'Region': u'Africa',
            'Television': '0.19'},
    u'MW': {'Internet': '0.93',
            'Print': '0.11',
            'Radio': '0.68',
            'Region': u'Africa',
            'Television': '0.68'},
    u'MX': {'Internet': '1.91',
            'Print': '0.06',
            'Radio': '1.84',
            'Region': u'Latin America',
            'Television': '1.84'},
    u'MY': {'Internet': '0.22',
            'Print': '1.07',
            'Radio': '0.91',
            'Region': u'Asia',
            'Television': '0.91'},
    u'NA': {'Internet': '0.16',
            'Print': '0.15',
            'Radio': '0.25',
            'Region': u'Africa',
            'Television': '0.25'},
    u'NE': {'Internet': '0.15',
            'Print': '0.08',
            'Radio': '0.71',
            'Region': u'Africa',
            'Television': '0.71'},
    u'NG': {'Internet': '2.19',
            'Print': '1.19',
            'Radio': '2.21',
            'Region': u'Africa',
            'Television': '2.21'},
    u'NI': {'Internet': '0.25',
            'Print': '0.26',
            'Radio': '0.41',
            'Region': u'Latin America',
            'Television': '0.41'},
    u'NL': {'Internet': '1.08',
            'Print': '1.19',
            'Radio': '0.68',
            'Region': u'Europe',
            'Television': '0.68'},
    u'NO': {'Internet': '0.59',
            'Print': '0.83',
            'Radio': '0.37',
            'Region': u'Europe',
            'Television': '0.37'},
    u'NP': {'Internet': '0.49',
            'Print': '0.30',
            'Radio': '0.88',
            'Region': u'Asia',
            'Television': '0.88'},
    u'NZ': {'Internet': '0.55',
            'Print': '0.68',
            'Radio': '0.35',
            'Region': u'Pacific Islands',
            'Television': '0.35'},
    u'PE': {'Internet': '0.95',
            'Print': '1.92',
            'Radio': '0.92',
            'Region': u'Latin America',
            'Television': '0.92'},
    u'PH': {'Internet': '1.68',
            'Print': '1.65',
            'Radio': '1.66',
            'Region': u'Asia',
            'Television': '1.66'},
    u'PK': {'Internet': '1.20',
            'Print': '0.06',
            'Radio': '2.25',
            'Region': u'Asia',
            'Television': '2.25'},
    u'PL': {'Internet': '1.36',
            'Print': '1.11',
            'Radio': '1.02',
            'Region': u'Europe',
            'Television': '1.02'},
    u'PR': {'Internet': '0.38',
            'Print': '0.53',
            'Radio': '0.32',
            'Region': u'Latin America',
            'Television': '0.32'},
    u'PS': {'Internet': '0.54',
            'Print': '0.00',
            'Radio': '0.59',
            'Region': u'Middle East',
            'Television': '0.59'},
    u'PT': {'Internet': '0.71',
            'Print': '0.63',
            'Radio': '0.54',
            'Region': u'Europe',
            'Television': '0.54'},
    u'PY': {'Internet': '0.38',
            'Print': '0.31',
            'Radio': '0.44',
            'Region': u'Latin America',
            'Television': '0.44'},
    u'RO': {'Internet': '0.90',
            'Print': '0.65',
            'Radio': '0.77',
            'Region': u'Europe',
            'Television': '0.77'},
    u'RS': {'Internet': '0.58',
            'Print': '0.58',
            'Radio': '0.51',
            'Region': u'Europe',
            'Television': '0.51'},
    u'SB': {'Internet': '0.06',
            'Print': '0.04',
            'Radio': '0.13',
            'Region': u'Pacific Islands',
            'Television': '0.13'},
    u'SD': {'Internet': '0.82',
            'Print': '0.60',
            'Radio': '1.03',
            'Region': u'Africa',
            'Television': '1.03'},
    u'SE': {'Internet': '0.78',
            'Print': '1.11',
            'Radio': '0.51',
            'Region': u'Europe',
            'Television': '0.51'},
    u'SI': {'Internet': '0.33',
            'Print': '0.31',
            'Radio': '0.24',
            'Region': u'Europe',
            'Television': '0.24'},
    u'SK': {'Internet': '0.57',
            'Print': '0.68',
            'Radio': '0.39',
            'Region': u'Europe',
            'Television': '0.39'},
    u'SL': {'Internet': '0.08',
            'Print': '0.07',
            'Radio': '0.41',
            'Region': u'Africa',
            'Television': '0.41'},
    u'SN': {'Internet': '0.48',
            'Print': '0.21',
            'Radio': '0.63',
            'Region': u'Africa',
            'Television': '0.63'},
    u'SO': {'Internet': '0.11',
            'Print': '0.68',
            'Radio': '0.54',
            'Region': u'Africa',
            'Television': '0.54'},
    u'SR': {'Internet': '0.12',
            'Print': '0.12',
            'Radio': '0.13',
            'Region': u'Carribean',
            'Television': '0.13'},
    u'SS': {'Internet': '0.15',
            'Print': '0.18',
            'Radio': '0.48',
            'Region': u'Africa',
            'Television': '0.48'},
    u'SV': {'Internet': '0.35',
            'Print': '0.32',
            'Radio': '0.42',
            'Region': u'Latin America',
            'Television': '0.42'},
    u'SZ': {'Internet': '0.15',
            'Print': '0.10',
            'Radio': '0.19',
            'Region': u'Africa',
            'Television': '0.19'},
    u'TD': {'Internet': '0.15',
            'Print': '0.00',
            'Radio': '0.60',
            'Region': u'Africa',
            'Television': '0.60'},
    u'TG': {'Internet': '0.15',
            'Print': '0.07',
            'Radio': '0.44',
            'Region': u'Africa',
            'Television': '0.44'},
    u'TN': {'Internet': '0.60',
            'Print': '0.31',
            'Radio': '0.55',
            'Region': u'Middle East',
            'Television': '0.55'},
    u'TO': {'Internet': '0.05',
            'Print': '0.05',
            'Radio': '0.05',
            'Region': u'Pacific Islands',
            'Television': '0.05'},
    u'TR': {'Internet': '1.59',
            'Print': '0.94',
            'Radio': '1.44',
            'Region': u'Europe',
            'Television': '1.44'},
    u'TT': {'Internet': '0.25',
            'Print': '0.18',
            'Radio': '0.19',
            'Region': u'Carribean',
            'Television': '0.19'},
    u'TW': {'Internet': '1.00',
            'Print': '0.68',
            'Radio': '0.80',
            'Region': u'Asia',
            'Television': '0.80'},
    u'TZ': {'Internet': '0.74',
            'Print': '0.35',
            'Radio': '1.18',
            'Region': u'Africa',
            'Television': '1.18'},
    u'UG': {'Internet': '0.68',
            'Print': '0.16',
            'Radio': '1.03',
            'Region': u'Africa',
            'Television': '1.03'},
    u'US': {'Internet': '4.48',
            'Print': '4.43',
            'Radio': '2.98',
            'Region': u'North America',
            'Television': '2.98'},
    u'UY': {'Internet': '0.38',
            'Print': '0.56',
            'Radio': '0.31',
            'Region': u'Latin America',
            'Television': '0.31'},
    u'VC': {'Internet': '0.05',
            'Print': '0.68',
            'Radio': '0.05',
            'Region': u'Carribean',
            'Television': '0.05'},
    u'VE': {'Internet': '1.02',
            'Print': '1.01',
            'Radio': '0.92',
            'Region': u'Latin America',
            'Television': '0.92'},
    u'VN': {'Internet': '1.69',
            'Print': '0.52',
            'Radio': '1.59',
            'Region': u'Asia',
            'Television': '1.59'},
    u'VU': {'Internet': '0.05',
            'Print': '0.58',
            'Radio': '0.08',
            'Region': u'Asia',
            'Television': '0.08'},
    u'WS': {'Internet': '0.04',
            'Print': '0.68',
            'Radio': '0.07',
            'Region': u'Pacific Islands',
            'Television': '0.07'},
    u'ZA': {'Internet': '1.34',
            'Print': '0.76',
            'Radio': '1.21',
            'Region': u'Africa',
            'Television': '1.21'},
    u'ZM': {'Internet': '0.41',
            'Print': '0.15',
            'Radio': '0.64',
            'Region': u'Africa',
            'Television': '0.64'},
    u'ZW': {'Internet': '0.45',
            'Print': '0.30',
            'Radio': '0.63',
            'Region': u'Africa',
            'Television': '0.63'}
}
