# Generated by Django 2.2.9 on 2020-01-14 13:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gmmp', '0002_auto_20191204_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
        ),
    ]
