# Generated by Django 2.2.16 on 2020-09-07 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gmmp', '0004_specialquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialquestions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='specialquestions',
            name='user',
        ),
        migrations.AddField(
            model_name='specialquestions',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
