# Generated by Django 2.2.18 on 2021-02-18 12:12

from django.db import migrations, models


def remove_duplicate_weights(apps, schema_editor):
    Weights = apps.get_model("reports", "Weights")
    db_alias = schema_editor.connection.alias

    # Remove all transnational since new one will be created with new code
    Weights.objects.using(db_alias).filter(country="T1").delete()

    # Remove any (country, media_type)  duplicate
    # Based on: https://stackoverflow.com/a/10290420
    last_seen_country = None
    last_seen_media_type = None
    weights = Weights.objects.using(db_alias).all().order_by("country", "media_type")
    for weight in weights:
        if (
            weight.country == last_seen_country
            and weight.media_type == last_seen_media_type
        ):
            weight.delete()
        else:
            last_seen_media_type = weight.media_type
            last_seen_country = weight.country


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_transnational_weights"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_weights,
            backwards,
        ),
    ]
