from __future__ import unicode_literals

from django.db import migrations
from django_countries import countries


COUNTRY_WEIGHTS = [
    {
        "Country": "AGO",
        "Print": "1.5",
        "Radio": "0.50",
        "TV": "0.61",
        "Internet": "0.29",
        "Twitter": "1.0",
    },
    {
        "Country": "BEN",
        "Print": "0.03",
        "Radio": "0.32",
        "TV": "0.87",
        "Internet": "0.26",
        "Twitter": "1.0",
    },
    {
        "Country": "BFA",
        "Print": "0.1",
        "Radio": "0.69",
        "TV": "0.64",
        "Internet": "0.19",
        "Twitter": "1.0",
    },
    {
        "Country": "CPV",
        "Print": "0.18",
        "Radio": "0.08",
        "TV": "0.09",
        "Internet": "0.12",
        "Twitter": "1.0",
    },
    {
        "Country": "CMR",
        "Print": "0.17",
        "Radio": "0.47",
        "TV": "0.74",
        "Internet": "0.29",
        "Twitter": "1.0",
    },
    {
        "Country": "CAF",
        "Print": "1.5",
        "Radio": "0.20",
        "TV": "0.24",
        "Internet": "0.03",
        "Twitter": "1.0",
    },
    {
        "Country": "TCD",
        "Print": "0.01",
        "Radio": "0.27",
        "TV": "0.98",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "COD",
        "Print": "0.28",
        "Radio": "1.39",
        "TV": "1.08",
        "Internet": "0.18",
        "Twitter": "1.0",
    },
    {
        "Country": "CIV",
        "Print": "1.5",
        "Radio": "0.47",
        "TV": "1.30",
        "Internet": "0.56",
        "Twitter": "1.0",
    },
    {
        "Country": "DJI",
        "Print": "1.5",
        "Radio": "0.53",
        "TV": "0.28",
        "Internet": "0.03",
        "Twitter": "1.0",
    },
    {
        "Country": "SWZ",
        "Print": "0.1",
        "Radio": "0.27",
        "TV": "0.12",
        "Internet": "0.12",
        "Twitter": "1.0",
    },
    {
        "Country": "ETH",
        "Print": "0.39",
        "Radio": "2.60",
        "TV": "1.29",
        "Internet": "0.47",
        "Twitter": "1.0",
    },
    {
        "Country": "GAB",
        "Print": "0.58",
        "Radio": "0.11",
        "TV": "0.22",
        "Internet": "0.22",
        "Twitter": "1.0",
    },
    {
        "Country": "GMB",
        "Print": "1.5",
        "Radio": "0.10",
        "TV": "0.39",
        "Internet": "0.07",
        "Twitter": "1.0",
    },
    {
        "Country": "GHA",
        "Print": "0.39",
        "Radio": "0.89",
        "TV": "0.69",
        "Internet": "0.53",
        "Twitter": "1.0",
    },
    {
        "Country": "GIN",
        "Print": "1.5",
        "Radio": "0.24",
        "TV": "0.39",
        "Internet": "0.15",
        "Twitter": "1.0",
    },
    {
        "Country": "KEN",
        "Print": "0.44",
        "Radio": "0.52",
        "TV": "0.90",
        "Internet": "1.58",
        "Twitter": "1.0",
    },
    {
        "Country": "MLI",
        "Print": "0.68",
        "Radio": "0.29",
        "TV": "0.47",
        "Internet": "0.63",
        "Twitter": "1.0",
    },
    {
        "Country": "MRT",
        "Print": "0.68",
        "Radio": "0.20",
        "TV": "0.24",
        "Internet": "0.11",
        "Twitter": "1.0",
    },
    {
        "Country": "MUS",
        "Print": "0.62",
        "Radio": "0.12",
        "TV": "0.14",
        "Internet": "0.19",
        "Twitter": "1.0",
    },
    {
        "Country": "NER",
        "Print": "0.08",
        "Radio": "2.18",
        "TV": "0.50",
        "Internet": "0.11",
        "Twitter": "1.0",
    },
    {
        "Country": "NGA",
        "Print": "1.19",
        "Radio": "1.29",
        "TV": "1.69",
        "Internet": "2.02",
        "Twitter": "1.0",
    },
    {
        "Country": "COG",
        "Print": "0.11",
        "Radio": "0.22",
        "TV": "0.26",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "RWA",
        "Print": "1.5",
        "Radio": "0.25",
        "TV": "0.52",
        "Internet": "0.40",
        "Twitter": "1.0",
    },
    {
        "Country": "SEN",
        "Print": "0.21",
        "Radio": "0.37",
        "TV": "0.48",
        "Internet": "0.55",
        "Twitter": "1.0",
    },
    {
        "Country": "SYC",
        "Print": "1.5",
        "Radio": "0.08",
        "TV": "0.09",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "SLE",
        "Print": "0.07",
        "Radio": "0.20",
        "TV": "0.72",
        "Internet": "0.09",
        "Twitter": "1.0",
    },
    {
        "Country": "SOM",
        "Print": "1.5",
        "Radio": "0.26",
        "TV": "0.46",
        "Internet": "0.09",
        "Twitter": "1.0",
    },
    {
        "Country": "ZAF",
        "Print": "0.76",
        "Radio": "1.30",
        "TV": "1.21",
        "Internet": "1.11",
        "Twitter": "1.0",
    },
    {
        "Country": "SSD",
        "Print": "0.18",
        "Radio": "0.81",
        "TV": "0.37",
        "Internet": "0.13",
        "Twitter": "1.0",
    },
    {
        "Country": "SDN",
        "Print": "0.6",
        "Radio": "0.61",
        "TV": "0.80",
        "Internet": "0.48",
        "Twitter": "1.0",
    },
    {
        "Country": "TZA",
        "Print": "0.35",
        "Radio": "1.17",
        "TV": "1.09",
        "Internet": "0.67",
        "Twitter": "1.0",
    },
    {
        "Country": "TGO",
        "Print": "0.07",
        "Radio": "0.20",
        "TV": "0.42",
        "Internet": "0.08",
        "Twitter": "1.0",
    },
    {
        "Country": "UGA",
        "Print": "0.16",
        "Radio": "0.45",
        "TV": "0.78",
        "Internet": "0.61",
        "Twitter": "1.0",
    },
    {
        "Country": "ZMB",
        "Print": "0.15",
        "Radio": "1.01",
        "TV": "0.46",
        "Internet": "0.39",
        "Twitter": "1.0",
    },
    {
        "Country": "ZWE",
        "Print": "0.3",
        "Radio": "0.93",
        "TV": "0.98",
        "Internet": "0.44",
        "Twitter": "1.0",
    },
    {
        "Country": "AFG",
        "Print": "0.33",
        "Radio": "0.57",
        "TV": "0.74",
        "Internet": "0.29",
        "Twitter": "1.0",
    },
    {
        "Country": "BGD",
        "Print": "3.63",
        "Radio": "0.98",
        "TV": "2.46",
        "Internet": "1.91",
        "Twitter": "1.0",
    },
    {
        "Country": "BTN",
        "Print": "0.68",
        "Radio": "0.47",
        "TV": "0.25",
        "Internet": "0.11",
        "Twitter": "1.0",
    },
    {
        "Country": "KHM",
        "Print": "1.5",
        "Radio": "2.13",
        "TV": "0.76",
        "Internet": "0.50",
        "Twitter": "1.0",
    },
    {
        "Country": "CHN",
        "Print": "1.5",
        "Radio": "4.98",
        "TV": "2.28",
        "Internet": "2.90",
        "Twitter": "1.0",
    },
    {
        "Country": "HKG",
        "Print": "1.5",
        "Radio": "0.29",
        "TV": "0.34",
        "Internet": "0.65",
        "Twitter": "1.0",
    },
    {
        "Country": "IND",
        "Print": "5.72",
        "Radio": "9.59",
        "TV": "3.43",
        "Internet": "1.90",
        "Twitter": "1.0",
    },
    {
        "Country": "IDN",
        "Print": "11",
        "Radio": "4.44",
        "TV": "3.17",
        "Internet": "2.73",
        "Twitter": "1.0",
    },
    {
        "Country": "JPN",
        "Print": "5.27",
        "Radio": "0.81",
        "TV": "1.69",
        "Internet": "2.57",
        "Twitter": "1.0",
    },
    {
        "Country": "KAZ",
        "Print": "1.5",
        "Radio": "0.32",
        "TV": "0.80",
        "Internet": "0.86",
        "Twitter": "1.0",
    },
    {
        "Country": "KGZ",
        "Print": "1.5",
        "Radio": "0.19",
        "TV": "0.33",
        "Internet": "0.26",
        "Twitter": "1.0",
    },
    {
        "Country": "MAC",
        "Print": "1.5",
        "Radio": "0.23",
        "TV": "0.14",
        "Internet": "0.18",
        "Twitter": "1.0",
    },
    {
        "Country": "MYS",
        "Print": "1.07",
        "Radio": "0.44",
        "TV": "0.77",
        "Internet": "1.21",
        "Twitter": "1.0",
    },
    {
        "Country": "MNG",
        "Print": "0.14",
        "Radio": "0.18",
        "TV": "0.34",
        "Internet": "0.29",
        "Twitter": "1.0",
    },
    {
        "Country": "MMR",
        "Print": "1.5",
        "Radio": "0.76",
        "TV": "1.18",
        "Internet": "0.64",
        "Twitter": "1.0",
    },
    {
        "Country": "NPL",
        "Print": "0.3",
        "Radio": "0.40",
        "TV": "0.70",
        "Internet": "0.74",
        "Twitter": "1.0",
    },
    {
        "Country": "PAK",
        "Print": "0.06",
        "Radio": "7.51",
        "TV": "2.68",
        "Internet": "1.27",
        "Twitter": "1.0",
    },
    {
        "Country": "PHL",
        "Print": "1.8",
        "Radio": "0.78",
        "TV": "1.95",
        "Internet": "1.93",
        "Twitter": "1.0",
    },
    {
        "Country": "KOR",
        "Print": "1.6",
        "Radio": "0.57",
        "TV": "1.19",
        "Internet": "1.86",
        "Twitter": "1.0",
    },
    {
        "Country": "TWN",
        "Print": "1.2",
        "Radio": "0.52",
        "TV": "0.68",
        "Internet": "1.23",
        "Twitter": "1.0",
    },
    {
        "Country": "TLS",
        "Print": "1.7",
        "Radio": "0.11",
        "TV": "0.30",
        "Internet": "0.08",
        "Twitter": "1.0",
    },
    {
        "Country": "UZB",
        "Print": "1.7",
        "Radio": "0.99",
        "TV": "1.11",
        "Internet": "0.79",
        "Twitter": "1.0",
    },
    {
        "Country": "VNM",
        "Print": "0.52",
        "Radio": "2.68",
        "TV": "1.60",
        "Internet": "1.82",
        "Twitter": "1.0",
    },
    {
        "Country": "ATG",
        "Print": "0.68",
        "Radio": "0.02",
        "TV": "0.09",
        "Internet": "0.07",
        "Twitter": "1.0",
    },
    {
        "Country": "BHS",
        "Print": "0.18",
        "Radio": "0.05",
        "TV": "0.08",
        "Internet": "0.14",
        "Twitter": "1.0",
    },
    {
        "Country": "BRB",
        "Print": "0.13",
        "Radio": "0.04",
        "TV": "0.15",
        "Internet": "0.11",
        "Twitter": "1.0",
    },
    {
        "Country": "BLZ",
        "Print": "0.68",
        "Radio": "0.11",
        "TV": "0.08",
        "Internet": "0.08",
        "Twitter": "1.0",
    },
    {
        "Country": "CYM",
        "Print": "1.7",
        "Radio": "0.05",
        "TV": "0.08",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "CUB",
        "Print": "0.12",
        "Radio": "0.35",
        "TV": "0.42",
        "Internet": "0.36",
        "Twitter": "1.0",
    },
    {
        "Country": "DMA",
        "Print": "1.7",
        "Radio": "0.02",
        "TV": "0.03",
        "Internet": "0.04",
        "Twitter": "1.0",
    },
    {
        "Country": "DOM",
        "Print": "0.68",
        "Radio": "0.33",
        "TV": "0.43",
        "Internet": "0.51",
        "Twitter": "1.0",
    },
    {
        "Country": "GRD",
        "Print": "0.68",
        "Radio": "0.03",
        "TV": "0.04",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "GUY",
        "Print": "0.15",
        "Radio": "0.09",
        "TV": "0.12",
        "Internet": "0.11",
        "Twitter": "1.0",
    },
    {
        "Country": "HTI",
        "Print": "0.17",
        "Radio": "0.25",
        "TV": "0.40",
        "Internet": "0.15",
        "Twitter": "1.0",
    },
    {
        "Country": "JAM",
        "Print": "0.27",
        "Radio": "0.30",
        "TV": "0.23",
        "Internet": "0.24",
        "Twitter": "1.0",
    },
    {
        "Country": "PRI",
        "Print": "0.53",
        "Radio": "0.18",
        "TV": "0.21",
        "Internet": "0.38",
        "Twitter": "1.0",
    },
    {
        "Country": "LCA",
        "Print": "0.18",
        "Radio": "0.03",
        "TV": "0.07",
        "Internet": "0.09",
        "Twitter": "1.0",
    },
    {
        "Country": "VCT",
        "Print": "0.68",
        "Radio": "0.03",
        "TV": "0.04",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "SUR",
        "Print": "0.12",
        "Radio": "0.08",
        "TV": "0.15",
        "Internet": "0.12",
        "Twitter": "1.0",
    },
    {
        "Country": "TTO",
        "Print": "0.18",
        "Radio": "0.09",
        "TV": "0.16",
        "Internet": "0.02",
        "Twitter": "1.0",
    },
    {
        "Country": "ALB",
        "Print": "1.7",
        "Radio": "0.13",
        "TV": "0.23",
        "Internet": "0.33",
        "Twitter": "1.0",
    },
    {
        "Country": "AUT",
        "Print": "0.58",
        "Radio": "0.30",
        "TV": "0.36",
        "Internet": "0.68",
        "Twitter": "1.0",
    },
    {
        "Country": "VLG",
        "Print": "0.7",
        "Radio": "0.89",
        "TV": "0.41",
        "Internet": "0.81",
        "Twitter": "1.0",
    },
    {
        "Country": "WAL",
        "Print": "0.7",
        "Radio": "0.89",
        "TV": "0.41",
        "Internet": "0.81",
        "Twitter": "1.0",
    },
    {
        "Country": "BIH",
        "Print": "0.68",
        "Radio": "0.19",
        "TV": "0.29",
        "Internet": "0.38",
        "Twitter": "1.0",
    },
    {
        "Country": "BGR",
        "Print": "0.41",
        "Radio": "0.26",
        "TV": "0.32",
        "Internet": "0.45",
        "Twitter": "1.0",
    },
    {
        "Country": "CYP",
        "Print": "0.13",
        "Radio": "0.19",
        "TV": "0.15",
        "Internet": "0.02",
        "Twitter": "1.0",
    },
    {
        "Country": "DNK",
        "Print": "0.74",
        "Radio": "0.24",
        "TV": "0.29",
        "Internet": "0.60",
        "Twitter": "1.0",
    },
    {
        "Country": "ENG",
        "Print": "1.7",
        "Radio": "1.37",
        "TV": "1.53",
        "Internet": "2.00",
        "Twitter": "1.0",
    },
    {
        "Country": "EST",
        "Print": "0.27",
        "Radio": "0.30",
        "TV": "0.14",
        "Internet": "0.29",
        "Twitter": "1.0",
    },
    {
        "Country": "FIN",
        "Print": "0.03",
        "Radio": "0.17",
        "TV": "0.36",
        "Internet": "0.55",
        "Twitter": "1.0",
    },
    {
        "Country": "FRA",
        "Print": "1.69",
        "Radio": "1.35",
        "TV": "1.51",
        "Internet": "1.89",
        "Twitter": "1.0",
    },
    {
        "Country": "GEO",
        "Print": "1.02",
        "Radio": "0.33",
        "TV": "0.36",
        "Internet": "0.34",
        "Twitter": "1.0",
    },
    {
        "Country": "DEU",
        "Print": "2.5",
        "Radio": "0.69",
        "TV": "1.43",
        "Internet": "2.23",
        "Twitter": "1.0",
    },
    {
        "Country": "GRC",
        "Print": "1.7",
        "Radio": "0.25",
        "TV": "0.51",
        "Internet": "0.61",
        "Twitter": "1.0",
    },
    {
        "Country": "GRL",
        "Print": "1.7",
        "Radio": "0.13",
        "TV": "0.07",
        "Internet": "0.06",
        "Twitter": "1.0",
    },
    {
        "Country": "HUN",
        "Print": "0.68",
        "Radio": "0.32",
        "TV": "0.38",
        "Internet": "0.72",
        "Twitter": "1.0",
    },
    {
        "Country": "ISL",
        "Print": "0.18",
        "Radio": "0.16",
        "TV": "0.07",
        "Internet": "0.15",
        "Twitter": "1.0",
    },
    {
        "Country": "IRL",
        "Print": "0.18",
        "Radio": "0.22",
        "TV": "0.29",
        "Internet": "0.52",
        "Twitter": "1.0",
    },
    {
        "Country": "ITA",
        "Print": "1.51",
        "Radio": "1.30",
        "TV": "1.45",
        "Internet": "1.82",
        "Twitter": "1.0",
    },
    {
        "Country": "LUX",
        "Print": "0.18",
        "Radio": "0.06",
        "TV": "0.23",
        "Internet": "0.20",
        "Twitter": "1.0",
    },
    {
        "Country": "MLT",
        "Print": "0.13",
        "Radio": "0.05",
        "TV": "0.11",
        "Internet": "0.15",
        "Twitter": "1.0",
    },
    {
        "Country": "MDA",
        "Print": "1.7",
        "Radio": "0.17",
        "TV": "0.23",
        "Internet": "0.33",
        "Twitter": "1.0",
    },
    {
        "Country": "NLD",
        "Print": "1.19",
        "Radio": "0.70",
        "TV": "0.78",
        "Internet": "1.01",
        "Twitter": "1.0",
    },
    {
        "Country": "NIR",
        "Print": "1.7",
        "Radio": "1.37",
        "TV": "1.53",
        "Internet": "2.00",
        "Twitter": "1.0",
    },
    {
        "Country": "NOR",
        "Print": "0.83",
        "Radio": "0.39",
        "TV": "0.44",
        "Internet": "0.58",
        "Twitter": "1.0",
    },
    {
        "Country": "POL",
        "Print": "1.11",
        "Radio": "1.06",
        "TV": "1.18",
        "Internet": "1.25",
        "Twitter": "1.0",
    },
    {
        "Country": "PRT",
        "Print": "0.63",
        "Radio": "0.32",
        "TV": "0.50",
        "Internet": "0.64",
        "Twitter": "1.0",
    },
    {
        "Country": "ROU",
        "Print": "0.65",
        "Radio": "0.75",
        "TV": "0.83",
        "Internet": "0.84",
        "Twitter": "1.0",
    },
    {
        "Country": "RUS",
        "Print": "1.7",
        "Radio": "0.92",
        "TV": "2.30",
        "Internet": "2.52",
        "Twitter": "1.0",
    },
    {
        "Country": "SCT",
        "Print": "1.7",
        "Radio": "1.37",
        "TV": "1.53",
        "Internet": "2.00",
        "Twitter": "1.0",
    },
    {
        "Country": "SRB",
        "Print": "0.58",
        "Radio": "1.40",
        "TV": "0.42",
        "Internet": "0.50",
        "Twitter": "1.0",
    },
    {
        "Country": "SVK",
        "Print": "1.7",
        "Radio": "0.18",
        "TV": "0.29",
        "Internet": "0.52",
        "Twitter": "1.0",
    },
    {
        "Country": "SVN",
        "Print": "1.7",
        "Radio": "0.15",
        "TV": "0.23",
        "Internet": "0.29",
        "Twitter": "1.0",
    },
    {
        "Country": "ESP",
        "Print": "1.35",
        "Radio": "0.52",
        "TV": "0.91",
        "Internet": "1.63",
        "Twitter": "1.0",
    },
    {
        "Country": "SWE",
        "Print": "1.11",
        "Radio": "0.24",
        "TV": "0.49",
        "Internet": "0.77",
        "Twitter": "1.0",
    },
    {
        "Country": "CHE",
        "Print": "0.94",
        "Radio": "0.30",
        "TV": "0.36",
        "Internet": "0.71",
        "Twitter": "1.0",
    },
    {
        "Country": "TUR",
        "Print": "0.94",
        "Radio": "1.57",
        "TV": "1.75",
        "Internet": "1.98",
        "Twitter": "1.0",
    },
    {
        "Country": "WLS",
        "Print": "1.7",
        "Radio": "1.37",
        "TV": "1.53",
        "Internet": "2.00",
        "Twitter": "1.0",
    },
    {
        "Country": "ARG",
        "Print": "0.74",
        "Radio": "1.13",
        "TV": "1.05",
        "Internet": "1.59",
        "Twitter": "1.0",
    },
    {
        "Country": "BOL",
        "Print": "0.42",
        "Radio": "0.25",
        "TV": "0.43",
        "Internet": "0.57",
        "Twitter": "1.0",
    },
    {
        "Country": "BRA",
        "Print": "1.7",
        "Radio": "1.14",
        "TV": "1.97",
        "Internet": "2.72",
        "Twitter": "1.0",
    },
    {
        "Country": "CHL",
        "Print": "0.37",
        "Radio": "0.45",
        "TV": "0.59",
        "Internet": "0.89",
        "Twitter": "1.0",
    },
    {
        "Country": "COL",
        "Print": "0.66",
        "Radio": "1.23",
        "TV": "1.15",
        "Internet": "1.18",
        "Twitter": "1.0",
    },
    {
        "Country": "CRI",
        "Print": "0.34",
        "Radio": "0.17",
        "TV": "0.30",
        "Internet": "0.51",
        "Twitter": "1.0",
    },
    {
        "Country": "ECU",
        "Print": "0.72",
        "Radio": "0.42",
        "TV": "0.66",
        "Internet": "0.85",
        "Twitter": "1.0",
    },
    {
        "Country": "SLV",
        "Print": "0.32",
        "Radio": "0.25",
        "TV": "0.48",
        "Internet": "0.37",
        "Twitter": "1.0",
    },
    {
        "Country": "GTM",
        "Print": "0.38",
        "Radio": "0.30",
        "TV": "0.52",
        "Internet": "0.43",
        "Twitter": "1.0",
    },
    {
        "Country": "HND",
        "Print": "1.7",
        "Radio": "0.23",
        "TV": "0.41",
        "Internet": "0.24",
        "Twitter": "1.0",
    },
    {
        "Country": "MEX",
        "Print": "0.06",
        "Radio": "0.86",
        "TV": "1.80",
        "Internet": "1.90",
        "Twitter": "1.0",
    },
    {
        "Country": "NIC",
        "Print": "0.26",
        "Radio": "0.26",
        "TV": "0.33",
        "Internet": "0.28",
        "Twitter": "1.0",
    },
    {
        "Country": "PRY",
        "Print": "0.31",
        "Radio": "0.20",
        "TV": "0.35",
        "Internet": "0.60",
        "Twitter": "1.0",
    },
    {
        "Country": "PER",
        "Print": "1.92",
        "Radio": "0.43",
        "TV": "0.76",
        "Internet": "1.00",
        "Twitter": "1.0",
    },
    {
        "Country": "URY",
        "Print": "0.56",
        "Radio": "0.14",
        "TV": "0.29",
        "Internet": "0.42",
        "Twitter": "1.0",
    },
    {
        "Country": "VEN",
        "Print": "1.01",
        "Radio": "0.90",
        "TV": "0.84",
        "Internet": "0.73",
        "Twitter": "1.0",
    },
    {
        "Country": "EGY",
        "Print": "1.43",
        "Radio": "1.64",
        "TV": "1.83",
        "Internet": "1.21",
        "Twitter": "1.0",
    },
    {
        "Country": "IRQ",
        "Print": "1.7",
        "Radio": "0.45",
        "TV": "0.78",
        "Internet": "0.75",
        "Twitter": "1.0",
    },
    {
        "Country": "ISR",
        "Print": "0.89",
        "Radio": "0.22",
        "TV": "0.35",
        "Internet": "0.60",
        "Twitter": "1.0",
    },
    {
        "Country": "JOR",
        "Print": "1.7",
        "Radio": "0.53",
        "TV": "0.59",
        "Internet": "0.68",
        "Twitter": "1.0",
    },
    {
        "Country": "LBN",
        "Print": "0.3",
        "Radio": "0.70",
        "TV": "0.42",
        "Internet": "0.62",
        "Twitter": "1.0",
    },
    {
        "Country": "MAR",
        "Print": "0.38",
        "Radio": "0.46",
        "TV": "0.74",
        "Internet": "1.01",
        "Twitter": "1.0",
    },
    {
        "Country": "PSE",
        "Print": "1.7",
        "Radio": "0.21",
        "TV": "0.25",
        "Internet": "0.34",
        "Twitter": "1.0",
    },
    {
        "Country": "TUN",
        "Print": "0.31",
        "Radio": "0.26",
        "TV": "0.66",
        "Internet": "0.60",
        "Twitter": "1.0",
    },
    {
        "Country": "CAN",
        "Print": "1.31",
        "Radio": "0.47",
        "TV": "0.81",
        "Internet": "1.47",
        "Twitter": "1.0",
    },
    {
        "Country": "USA",
        "Print": "4.43",
        "Radio": "3.07",
        "TV": "3.43",
        "Internet": "4.44",
        "Twitter": "1.0",
    },
    {
        "Country": "AUS",
        "Print": "0.98",
        "Radio": "0.38",
        "TV": "0.66",
        "Internet": "1.11",
        "Twitter": "1.0",
    },
    {
        "Country": "FJI",
        "Print": "0.12",
        "Radio": "0.25",
        "TV": "0.11",
        "Internet": "0.13",
        "Twitter": "1.0",
    },
    {
        "Country": "NZL",
        "Print": "0.68",
        "Radio": "0.22",
        "TV": "0.27",
        "Internet": "0.51",
        "Twitter": "1.0",
    },
    {
        "Country": "PNG",
        "Print": "1.7",
        "Radio": "0.22",
        "TV": "0.45",
        "Internet": "0.08",
        "Twitter": "1.0",
    },
    {
        "Country": "WSM",
        "Print": "1.7",
        "Radio": "0.04",
        "TV": "0.05",
        "Internet": "0.01",
        "Twitter": "1.0",
    },
    {
        "Country": "TON",
        "Print": "1.7",
        "Radio": "0.02",
        "TV": "0.09",
        "Internet": "0.04",
        "Twitter": "1.0",
    },
    {
        "Country": "VUT",
        "Print": "1.7",
        "Radio": "0.05",
        "TV": "0.14",
        "Internet": "0.01",
        "Twitter": "1.0",
    },
    {
        "Country": "BWA",
        "Print": "1.7",
        "Radio": "0.15",
        "TV": "0.18",
        "Internet": "0.18",
        "Twitter": "1.0",
    },
    {
        "Country": "MWI",
        "Print": "0.11",
        "Radio": "0.30",
        "TV": "0.52",
        "Internet": "0.14",
        "Twitter": "1.0",
    },
    {
        "Country": "XIN",
        "Print": "1.0",
        "Radio": "1.0",
        "TV": "1.0",
        "Internet": "1.0",
        "Twitter": "1.0",
    },
]


def populate_proxy_weights(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    # Update countries region Pacific -> Pacific Islands
    CountryRegion = apps.get_model("forms", "CountryRegion")
    CountryRegion.objects.using(db_alias).filter(region="Pacific").update(
        region="Pacific Islands"
    )

    # Update weights to proxy weights pending finalization
    Weights = apps.get_model("reports", "Weights")
    for item in COUNTRY_WEIGHTS:
        country_alpha3 = item.pop("Country")
        country = countries.alpha2(country_alpha3)
        for media_type, weight in item.items():
            Weights.objects.using(db_alias).update_or_create(
                country=country, media_type=media_type, defaults={"weight": weight}
            )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_unique_country_mediatype"),
    ]

    operations = [
        migrations.RunPython(
            populate_proxy_weights,
            backwards,
        ),
    ]
