# Generated by Django 2.2.18 on 2021-02-18 12:12

from django.db import migrations, models


def delete_tv_media_type_weights(apps, schema_editor):
    Weights = apps.get_model("reports", "Weights")
    db_alias = schema_editor.connection.alias

    # Weights with wrong media type 'TV' were accidentally added by
    # `import-weights` command. The command has been updated to use
    # 'Television' as media type. It is best to delete existing rows
    # and import weights afresh.
    Weights.objects.using(db_alias).filter(media_type="TV").delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_gsheetcountryweights"),
    ]

    operations = [
        migrations.RunPython(
            delete_tv_media_type_weights,
            backwards,
        ),
    ]
