# Generated by Django 2.2.19 on 2021-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_delete_tv_media_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weights',
            name='country_media_type_key',
        ),
        migrations.AddField(
            model_name='weights',
            name='weight_type',
            field=models.CharField(choices=[('R', 'Regional'), ('G', 'Global')], default='G', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='weights',
            constraint=models.UniqueConstraint(fields=('country', 'media_type', 'weight_type'), name='country_media_weight_type_key'),
        ),
    ]
