# Generated by Django 2.2.19 on 2021-03-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_weights_weight_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GSheetCountryWeights',
            new_name='GSheetGlobalCountryWeights',
        ),
        migrations.RenameField(
            model_name='gsheetglobalcountryweights',
            old_name='tv_weight',
            new_name='television_weight',
        ),
    ]
