name: Dokku CD
on:
  push:
    branches: [ master ]
env:
  DOKKU_APP_NAME: 'gmmp'
  DOKKU_HOST: 'gmmp.dev.codeforafrica.org'
  DOKKU_REMOTE_BRANCH: 'master'
  GIT_PUSH_FLAGS: '--force'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ env.DOKKU_HOST }}
            app-name: ${{ env.DOKKU_APP_NAME }}
            remote-branch: ${{ env.DOKKU_REMOTE_BRANCH }}
            git-push-flags: ${{ env.GIT_PUSH_FLAGS }}
