# Generated by Django 2.2.17 on 2020-12-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("sheet_name", models.CharField(max_length=255)),
                ("sheet_tab", models.CharField(max_length=255)),
                ("sheet_row", models.IntegerField()),
            ],
        ),
    ]
