# Generated by Django 2.2.17 on 2020-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coding_sheets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnProccessedRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("sheet_name", models.CharField(max_length=255)),
                ("sheet_tab", models.CharField(max_length=255)),
                ("sheet_row", models.IntegerField()),
                ("row_error", models.TextField()),
            ],
        ),
    ]
